package gui;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import marklin.MarklinControlStation;

/**
 *
 * @author adamo
 */
public class About extends javax.swing.JPanel {

    public About()
    {
        initComponents();
        
        versionLabel.setText(versionLabel.getText().replace("xxx", MarklinControlStation.RAW_VERSION));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        linkLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        linkLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();

        linkLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        linkLabel.setForeground(new java.awt.Color(0, 51, 255));
        linkLabel.setText("Readme (Instructions & API)");
        linkLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkLabelMouseClicked(evt);
            }
        });

        jLabel1.setText("|");

        linkLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        linkLabel1.setForeground(new java.awt.Color(0, 51, 255));
        linkLabel1.setText("Support this Project");
        linkLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("TrainControl is free software that allows you to conveniently control & fully");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Designed for users with many trains and accessories where two knobs ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("automate large model train layouts using your computer and keyboard. ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("just aren't enough. Requires the Marklin Central Station 2 or 3 controller.");

        versionLabel.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        versionLabel.setText("Version xxx, developed and maintained by Adam Oest.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(linkLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(linkLabel1))
                    .addComponent(versionLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addComponent(versionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linkLabel)
                    .addComponent(jLabel1)
                    .addComponent(linkLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void linkLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkLabelMouseClicked
        try 
        {
            Desktop.getDesktop().browse(new URI("https://github.com/bob123456678/TrainControl/tree/master#readme"));
        } catch (IOException | URISyntaxException e1) { }
    }//GEN-LAST:event_linkLabelMouseClicked

    private void linkLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkLabel1MouseClicked
        try 
        {
            Desktop.getDesktop().browse(new URI("https://buymeacoffee.com/traincontrol"));
        } catch (IOException | URISyntaxException e1) { }
    }//GEN-LAST:event_linkLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel linkLabel;
    private javax.swing.JLabel linkLabel1;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables
}
