/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import marklin.MarklinLocomotive;

/**
 *
 * @author Adam
 */
public class LocomotiveSelectorItem extends javax.swing.JPanel {
    
    private MarklinLocomotive loc;
    private TrainControlUI ui;
    
    /**
     * Creates new form LocomotiveSelectorItem
     * @param loc
     * @param ui
     */
    public LocomotiveSelectorItem(MarklinLocomotive loc, TrainControlUI ui) {
        initComponents();
        
        this.loc = loc;
        this.ui = ui;
                
        this.LocLabel.setText(loc.getName());
        
        if (ui.LOAD_IMAGES && loc.getImageURL() != null)
        {
            try 
            {
                locIcon.setIcon(new javax.swing.ImageIcon(
                    ui.getLocImage(loc.getImageURL(), 85)
                ));      
                locIcon.setText("");
            }
            catch (Exception e)
            {
                locIcon.setIcon(null);
            }
        }
        else
        {
            locIcon.setIcon(null);
        }

    }
    
    public String getText()
    {
        return this.loc.getName();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        locIcon = new javax.swing.JLabel();
        LocLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(140, 95));
        setMinimumSize(new java.awt.Dimension(140, 95));
        setPreferredSize(new java.awt.Dimension(140, 95));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        locIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                locIconMouseReleased(evt);
            }
        });

        LocLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LocLabel.setText("jLabel1");
        LocLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LocLabelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LocLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(locIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(locIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LocLabel)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        ui.mapLocToCurrentButton(loc.getName());
    }//GEN-LAST:event_formMouseReleased

    private void LocLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LocLabelMouseReleased
        formMouseReleased(evt);
    }//GEN-LAST:event_LocLabelMouseReleased

    private void locIconMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_locIconMouseReleased
        formMouseReleased(evt);
    }//GEN-LAST:event_locIconMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LocLabel;
    private javax.swing.JLabel locIcon;
    // End of variables declaration//GEN-END:variables
}
