package org.traincontrol.gui;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import org.traincontrol.marklin.MarklinControlStation;

/**
 *
 * @author adam
 */
public class About extends javax.swing.JPanel
{
    public About()
    {
        initComponents();
        
        versionLabel.setText(versionLabel.getText().replace("{0}", MarklinControlStation.RAW_VERSION));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        linkLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        linkLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();

        linkLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        linkLabel.setForeground(new java.awt.Color(0, 0, 115));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/traincontrol/resources/messages"); // NOI18N
        linkLabel.setText(bundle.getString("ui.readmeLink")); // NOI18N
        linkLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkLabelMouseClicked(evt);
            }
        });

        jLabel1.setText("|");

        linkLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        linkLabel1.setForeground(new java.awt.Color(0, 0, 115));
        linkLabel1.setText(bundle.getString("ui.supportLink")); // NOI18N
        linkLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText(bundle.getString("ui.aboutText")); // NOI18N

        versionLabel.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        versionLabel.setText(bundle.getString("ui.versionAboutString")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(linkLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(linkLabel1))
                    .addComponent(versionLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(versionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linkLabel)
                    .addComponent(jLabel1)
                    .addComponent(linkLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void linkLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkLabelMouseClicked
        try 
        {
            Desktop.getDesktop().browse(new URI("https://github.com/bob123456678/TrainControl/tree/master#readme"));
        } catch (IOException | URISyntaxException e1) { }
    }//GEN-LAST:event_linkLabelMouseClicked

    private void linkLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkLabel1MouseClicked
        try 
        {
            Desktop.getDesktop().browse(new URI("https://buymeacoffee.com/traincontrol"));
        } catch (IOException | URISyntaxException e1) { }
    }//GEN-LAST:event_linkLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel linkLabel;
    private javax.swing.JLabel linkLabel1;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables
}
