package org.traincontrol.gui;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JPanel;
import org.traincontrol.base.LayoutDiagram;

/**
 * Popup representing a track diagram
 * @author Adam
 */
public class LayoutPopupUI extends PositionAwareJFrame
{
    private final TrainControlUI parent;
    private final int size;
    private LayoutDiagram layout;
    private int pageIndex;
    
    /**
     * Popup window showing train layouts
     * @param l reference to the layout
     * @param size size of each tile, in pixels
     * @param ui
     * @param pageIndex
     */
    public LayoutPopupUI(LayoutDiagram l, int size, TrainControlUI ui, int pageIndex)
    {
        initComponents();
        
        this.ExtLayoutPanel.setLayout(new FlowLayout());
        this.parent = ui;
        this.size = size;
        this.layout = l;
        this.pageIndex = pageIndex;
    }

    // The grid on screen now, so that the next one can tell it to stop
    private LayoutGrid grid;
    
    private void drawGrid()
    {
        // The grid being replaced is told to stop first.
        //
        // A LayoutGrid keeps two Swing timers - one that shows the diagram when its tiles have
        // decoded, one that puts a spinner up if they are slow - and both go on firing into the panel
        // after the panel has been emptied.  The outgoing grid then drops a spinner into the page the
        // NEW grid has just drawn.  Both other places that build a grid over an existing panel call
        // this; this one did not.
        if (this.grid != null) this.grid.discard();

        this.ExtLayoutPanel.removeAll();

        LayoutGrid grid = new LayoutGrid(this.layout, size,
            this.ExtLayoutPanel, 
            this,
            true, parent);
        
        this.grid = grid;

        setTitle(this.layout.getName() + this.parent.getWindowTitleString());

        // Scale the popup according to the size of the layout
        this.setPreferredSize(new Dimension(grid.maxWidth + 100, grid.maxHeight + 100));
        pack();
        
        // Remember window location for different layouts and sizes
        this.setWindowIndex(this.layout.getName()+ "_" + this.getLayoutSize());
        
        // Only load location once
        if (!this.isLoaded())
        {
            loadWindowBounds();
        }
        
        saveWindowBounds();
        
        // Update auto layout station labels on the track diagram
        this.parent.updateVisiblePoints();
    }
    
    public String getLayoutTitle()
    {
        return this.layout.getName();
    }
    
    public void render()
    {        
        this.setAlwaysOnTop(parent.isAlwaysOnTop());
                      
        drawGrid();
             
        setVisible(true);
        
        // Hide the window on close so that LayoutLabels know they can be deleted
        addWindowListener(new WindowAdapter()
        {
            @Override
            public void windowClosing(WindowEvent e)
            {
                e.getComponent().setVisible(false);
            }
        });
    }
    
    /**
     * Refreshes the contents of the layout
     */
    public void refreshDiagram()
    {
        this.goToLayoutPage(this.pageIndex);
    }
    
    /**
     * Updates the layout page
     * @param index
     */
    public void goToLayoutPage(int index)
    {
        javax.swing.SwingUtilities.invokeLater( () -> 
        {
            int page = index + 1;

            if (index < this.parent.getModel().getLayoutList().size() && index >= 0)
            {
                this.parent.getModel().logf("layout.ui.logPopupLayoutUpdate", page);

                this.layout = this.parent.getModel().getLayout(
                    this.parent.getModel().getLayoutList().get(index)
                );

                drawGrid();
                this.repaint();

                // Update saved index
                this.pageIndex = index;
            }
            else
            {
                this.parent.getModel().logf("layout.ui.logPopupLayoutPageNotExist", page);
            }
        });
    }
    
    public JPanel getPanel()
    {
        return this.ExtLayoutPanel;
    }
    
    public int getLayoutSize()
    {
        return this.size;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ExtLayoutPanel = new javax.swing.JPanel();

        setIconImage(Toolkit.getDefaultToolkit().getImage(TrainControlUI.class.getResource("resources/locicon.png")));
        setMinimumSize(new java.awt.Dimension(150, 150));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        ExtLayoutPanel.setBackground(new java.awt.Color(255, 255, 255));
        ExtLayoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExtLayoutPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ExtLayoutPanelLayout = new javax.swing.GroupLayout(ExtLayoutPanel);
        ExtLayoutPanel.setLayout(ExtLayoutPanelLayout);
        ExtLayoutPanelLayout.setHorizontalGroup(
            ExtLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );
        ExtLayoutPanelLayout.setVerticalGroup(
            ExtLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(ExtLayoutPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        parent.childWindowKeyEvent(evt);
    }//GEN-LAST:event_formKeyPressed

    private void ExtLayoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExtLayoutPanelMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3)
        {
            // Same as the main window: the menu carries the setup now, so it is offered whether or not
            // a layout has been built yet
            LayoutRightclickAutonomyMenu.showFor(parent, null, null,
                evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_ExtLayoutPanelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ExtLayoutPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
