package org.traincontrol.base;

import java.util.ArrayList;
import java.util.Collections;
import java.util.EnumMap;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.traincontrol.base.Accessory.accessorySetting;
import org.traincontrol.base.LayoutDiagramComponent.componentType;

/**
 * The port map: which sides of a track diagram tile are connected to each other.
 *
 * This is the seed for autonomy's tile graph.  Geometry proposes the connections; the user confirms or
 * corrects them in the diagram editor, so a misreading here shows up as a visibly wrong line rather than
 * as a silently wrong edge.
 *
 * The map is uniformly state-indexed: ports(type, orientation, state) returns the routes that exist in
 * that state.  Switches REPLACE their routes when thrown rather than adding to them - a SWITCH_LEFT is
 * N-S unswitched and S-W switched, with N unreachable once thrown - so there is no notion of a "common"
 * leg, a "branch", or a toe anywhere in this class.  Non-switch tiles have a single state.
 *
 * Orientation follows getImage: the icon is rotated by (4 - orientation) * 90 degrees clockwise, so
 * orientation o applies (4 - o) quarter turns of N->E->S->W.  The domain of valid orientations is
 * whatever LayoutDiagramComponent.getNumOrientations() allows for the type (1, 2 or 4) - asking for
 * orientation 3 of a STRAIGHT is a bug, not a rotation.
 *
 * The table below was verified tile by tile against the icon art (see docs/plans/portmap-verification.png,
 * generated by docs/plans/portmap-verification.py).  That script holds the same data; if this table
 * changes, change it there too so the picture and the code cannot drift apart.
 *
 * @author Adam
 */
public class TilePorts
{
    /**
     * A side of a tile.  Clockwise order, which is what rotation walks.
     */
    public static enum Side
    {
        N, E, S, W;

        /**
         * Rotates this side by the given number of quarter turns clockwise.
         * @param quarterTurns
         * @return
         */
        public Side rotateClockwise(int quarterTurns)
        {
            return values()[(ordinal() + ((quarterTurns % 4) + 4) % 4) % 4];
        }

        /**
         * The side directly across the tile.
         * @return
         */
        public Side opposite()
        {
            return rotateClockwise(2);
        }
    }

    /**
     * Which of a tile's accessories a command applies to.  A three-way turnout is the only type that
     * uses SECONDARY, via LayoutDiagramComponent.getAccessory2().
     */
    public static enum AccessorySlot
    {
        PRIMARY, SECONDARY
    }

    /**
     * A path through a tile between two of its sides.
     *
     * Normally traversable both ways.  A CUSTOM_PERM_* turnout - a defective switch with no address,
     * which cannot be thrown - is the exception: it may only be entered from a branch and left at the
     * toe, because with the blades stuck in an unknown position a facing move cannot choose a branch,
     * while a trailing move merges safely whatever the blades are doing.  That restriction lives here
     * because it is a property of the hardware, not a user choice; user-authored direction is stored
     * separately and ANDs with it.
     */
    public static class Route
    {
        private final Side a;
        private final Side b;
        private final Side directedToward;

        Route(Side a, Side b, Side directedToward)
        {
            this.a = a;
            this.b = b;
            this.directedToward = directedToward;
        }

        public Side getA()
        {
            return a;
        }

        public Side getB()
        {
            return b;
        }

        /**
         * The only side this route may be travelled toward, or null when it is traversable both ways.
         * @return
         */
        public Side getDirectedToward()
        {
            return directedToward;
        }

        /**
         * @param side
         * @return true if this route touches the given side
         */
        public boolean touches(Side side)
        {
            return a == side || b == side;
        }

        /**
         * The far side of this route from the one given, or null if it does not touch that side.
         * @param from
         * @return
         */
        public Side other(Side from)
        {
            if (a == from) return b;
            if (b == from) return a;
            return null;
        }

        /**
         * Whether a train may enter at the given side and leave at the other.
         * @param from
         * @return
         */
        public boolean isTraversableFrom(Side from)
        {
            if (!touches(from)) return false;
            return directedToward == null || directedToward == other(from);
        }

        /**
         * Rotates this route by the given number of quarter turns clockwise.
         * @param quarterTurns
         * @return
         */
        public Route rotateClockwise(int quarterTurns)
        {
            return new Route(
                a.rotateClockwise(quarterTurns),
                b.rotateClockwise(quarterTurns),
                directedToward == null ? null : directedToward.rotateClockwise(quarterTurns)
            );
        }

        @Override
        public String toString()
        {
            if (directedToward == null)
            {
                return a.toString() + "-" + b.toString();
            }

            return other(directedToward).toString() + "->" + directedToward.toString();
        }
    }

    /**
     * One switch position (or the single position of a fixed tile): the routes it offers and the
     * accessory settings that select it.
     */
    public static class TileState
    {
        private final List<Route> routes;
        private final Map<AccessorySlot, accessorySetting> commands;

        TileState(List<Route> routes, Map<AccessorySlot, accessorySetting> commands)
        {
            this.routes = Collections.unmodifiableList(routes);
            this.commands = Collections.unmodifiableMap(commands);
        }

        public List<Route> getRoutes()
        {
            return routes;
        }

        /**
         * The accessory settings that must be commanded for this state to hold.
         *
         * Every address the tile has is always specified - a three-way's straight route commands both of
         * its addresses to straight, not neither - because straight and thrown always differentiate and
         * leaving an address unmentioned would let a previously thrown branch stay selected.
         * @return
         */
        public Map<AccessorySlot, accessorySetting> getCommands()
        {
            return commands;
        }

        TileState rotateClockwise(int quarterTurns)
        {
            List<Route> rotated = new ArrayList<>();

            for (Route r : routes)
            {
                rotated.add(r.rotateClockwise(quarterTurns));
            }

            return new TileState(rotated, commands);
        }
    }

    // The port map at orientation 0, by type.  Index in the list is the state index.
    private static final Map<componentType, List<TileState>> PORTS = new EnumMap<>(componentType.class);

    // Types that cannot appear on a diagram used for autonomy at all
    private static final Map<componentType, Boolean> DISQUALIFIED = new EnumMap<>(componentType.class);

    // Types autonomy stops at rather than routes through
    private static final Map<componentType, Boolean> TERMINATOR = new EnumMap<>(componentType.class);

    // Types whose second port is a user-paired portal to another tile, possibly on another page
    private static final Map<componentType, Boolean> PORTAL = new EnumMap<>(componentType.class);

    static
    {
        // --- plain track -------------------------------------------------------------------------
        fixed(componentType.STRAIGHT, route(Side.E, Side.W));
        fixed(componentType.CURVE, route(Side.E, Side.S));
        fixed(componentType.DOUBLE_CURVE, route(Side.N, Side.W), route(Side.E, Side.S));

        // Feedback tiles are plain track that also carries an s88.  Every one of them becomes a Point.
        fixed(componentType.FEEDBACK, route(Side.E, Side.W));
        fixed(componentType.FEEDBACK_CURVE, route(Side.E, Side.S));
        fixed(componentType.FEEDBACK_DOUBLE_CURVE, route(Side.N, Side.W), route(Side.E, Side.S));

        // A signal does not branch - topologically it is a straight - but it must be GREEN for a train to
        // pass, so traversing one carries a command just as throwing a switch does.  Expressing that here
        // rather than in the reducer means the reducer needs no special case: it gathers commands along a
        // path uniformly, and a signal contributes one like anything else.  Setting other signals to RED
        // for safety is left to conditional routes, which is where users already do it.
        signalled(componentType.SIGNAL, accessorySetting.GREEN, route(Side.E, Side.W));

        // An uncoupler has an address too, but firing it is an operation the user asks for, not a
        // condition of passing over the tile, so nothing is commanded when a path crosses one.
        fixed(componentType.UNCOUPLER, route(Side.E, Side.W));

        // --- crossings ---------------------------------------------------------------------------
        // Two independent through routes that share the tile.  They never join, but they do conflict:
        // one physical crossing, so edges using either are mutually exclusive.
        fixed(componentType.CROSSING, route(Side.N, Side.S), route(Side.E, Side.W));

        // Grade separated - one track physically above the other - so the two routes neither join nor
        // conflict.  This is the single exception to "shared tile means mutually exclusive".
        fixed(componentType.OVERPASS, route(Side.N, Side.S), route(Side.E, Side.W));

        // --- dead ends and portals ---------------------------------------------------------------
        fixed(componentType.END, stub(Side.N));

        // A tunnel connects normally on its visible side; its continuation is a user-paired tile.
        fixed(componentType.TUNNEL, stub(Side.S));
        PORTAL.put(componentType.TUNNEL, Boolean.TRUE);

        // A link's art is a box holding an east-pointing arrow: the track attaches on the side opposite
        // the arrow head, and the arrow points away toward the page being jumped to.
        fixed(componentType.LINK, stub(Side.W));
        PORTAL.put(componentType.LINK, Boolean.TRUE);

        // --- switches ----------------------------------------------------------------------------
        // Thrown replaces the route set rather than adding to it.
        switched(componentType.SWITCH_LEFT,
            state(commands(accessorySetting.STRAIGHT), route(Side.N, Side.S)),
            state(commands(accessorySetting.TURN), route(Side.S, Side.W)));

        switched(componentType.SWITCH_RIGHT,
            state(commands(accessorySetting.STRAIGHT), route(Side.N, Side.S)),
            state(commands(accessorySetting.TURN), route(Side.S, Side.E)));

        // A Y turnout has no straight route in either position.
        switched(componentType.SWITCH_Y,
            state(commands(accessorySetting.STRAIGHT), route(Side.S, Side.W)),
            state(commands(accessorySetting.TURN), route(Side.S, Side.E)));

        // Two addresses, three positions.  Both addresses are always commanded.
        switched(componentType.SWITCH_THREE,
            state(commands(accessorySetting.STRAIGHT, accessorySetting.STRAIGHT), route(Side.N, Side.S)),
            state(commands(accessorySetting.TURN, accessorySetting.STRAIGHT), route(Side.S, Side.W)),
            state(commands(accessorySetting.STRAIGHT, accessorySetting.TURN), route(Side.S, Side.E)));

        // A double slip: the two through routes when straight, the two diagonals when thrown.  It is the
        // only tile that contributes commands in both states rather than only when thrown.
        switched(componentType.SWITCH_CROSSING,
            state(commands(accessorySetting.STRAIGHT), route(Side.N, Side.S), route(Side.E, Side.W)),
            state(commands(accessorySetting.TURN), route(Side.N, Side.W), route(Side.S, Side.E)));

        // --- defective switches ------------------------------------------------------------------
        // No address, so they cannot be thrown: trailing moves only, into the toe at S.
        fixed(componentType.CUSTOM_PERM_LEFT,
            into(Side.S, Side.N), into(Side.S, Side.W));
        fixed(componentType.CUSTOM_PERM_RIGHT,
            into(Side.S, Side.N), into(Side.S, Side.E));
        fixed(componentType.CUSTOM_PERM_Y,
            into(Side.S, Side.W), into(Side.S, Side.E));
        fixed(componentType.CUSTOM_PERM_THREEWAY,
            into(Side.S, Side.N), into(Side.S, Side.W), into(Side.S, Side.E));

        // --- not routable ------------------------------------------------------------------------
        // Scissors are a drawing convention: two tiles depicting one double slip.  Their topology cannot
        // be expressed per tile, so a diagram carrying one cannot be used for autonomy at all.
        DISQUALIFIED.put(componentType.CUSTOM_SCISSORS, Boolean.TRUE);
        DISQUALIFIED.put(componentType.CUSTOM_PERM_SCISSORS, Boolean.TRUE);

        // A turntable connects any radial to any other under manual control and has no static port map.
        TERMINATOR.put(componentType.TURNTABLE, Boolean.TRUE);

        // --- decoration --------------------------------------------------------------------------
        fixed(componentType.LAMP);
        fixed(componentType.ROUTE);
        fixed(componentType.TEXT);
    }

    private TilePorts()
    {
    }

    /**
     * The routes a tile of this type offers, in the given state, at the given orientation.
     *
     * @param type
     * @param orientation 0 .. getNumOrientations() - 1 for the type
     * @param state 0 .. getStateCount() - 1 for the type
     * @return the routes, empty for decorative, disqualified, terminator and unmapped types
     */
    public static List<Route> ports(componentType type, int orientation, int state)
    {
        List<TileState> states = PORTS.get(type);

        if (states == null || state < 0 || state >= states.size())
        {
            return Collections.emptyList();
        }

        // getImage rotates by (4 - orientation) * 90 degrees clockwise, so the ports follow
        return states.get(state).rotateClockwise(4 - normalizeOrientation(type, orientation)).getRoutes();
    }

    /**
     * The accessory settings that select the given state.  Empty for tiles with nothing to command.
     * @param type
     * @param state
     * @return
     */
    public static Map<AccessorySlot, accessorySetting> commands(componentType type, int state)
    {
        List<TileState> states = PORTS.get(type);

        if (states == null || state < 0 || state >= states.size())
        {
            return Collections.emptyMap();
        }

        return states.get(state).getCommands();
    }

    /**
     * How many positions this type has: 1 for fixed track, 2 for an ordinary switch, 3 for a three-way.
     * @param type
     * @return
     */
    public static int getStateCount(componentType type)
    {
        List<TileState> states = PORTS.get(type);

        return states == null ? 0 : states.size();
    }

    /**
     * True if this type carries a second, user-paired port to a tile elsewhere - a tunnel or a page link.
     * The pairing is authored, never inferred, and an unpaired portal simply does not connect.
     * @param type
     * @return
     */
    public static boolean hasPortal(componentType type)
    {
        return PORTAL.containsKey(type);
    }

    /**
     * True if a diagram carrying this type cannot be used for autonomy.  Scissors tiles are a drawing
     * convention rather than a routing element, so they are refused rather than ignored: ignoring one
     * would leave a hole that traces quietly route around.
     * @param type
     * @return
     */
    public static boolean isDisqualified(componentType type)
    {
        return DISQUALIFIED.containsKey(type);
    }

    /**
     * True if autonomy stops at this type rather than routing through it.
     * @param type
     * @return
     */
    public static boolean isTerminator(componentType type)
    {
        return TERMINATOR.containsKey(type);
    }

    /**
     * True if this type has any routes at all in any state - false for decoration, turntables and
     * disqualified tiles.
     * @param type
     * @return
     */
    public static boolean isRoutable(componentType type)
    {
        if (isDisqualified(type) || isTerminator(type)) return false;

        for (int state = 0; state < getStateCount(type); state++)
        {
            if (!ports(type, 0, state).isEmpty()) return true;
        }

        return false;
    }

    /**
     * Guards the orientation against the type's rotational symmetry.  A STRAIGHT has two distinct
     * orientations, a CROSSING one; asking beyond that is a caller bug, so it is reduced rather than
     * silently producing a rotation the diagram can never contain.
     */
    private static int normalizeOrientation(componentType type, int orientation)
    {
        int allowed = numOrientations(type);

        return ((orientation % allowed) + allowed) % allowed;
    }

    /**
     * Mirrors LayoutDiagramComponent.getNumOrientations() without needing an instance.
     * @param type
     * @return
     */
    public static int numOrientations(componentType type)
    {
        if (type == componentType.STRAIGHT || type == componentType.FEEDBACK
                || type == componentType.ROUTE || type == componentType.SWITCH_CROSSING
                || type == componentType.OVERPASS)
        {
            return 2;
        }
        else if (type == componentType.TURNTABLE || type == componentType.CROSSING)
        {
            return 1;
        }

        return 4;
    }

    // --- table construction helpers ---------------------------------------------------------------

    private static Route route(Side a, Side b)
    {
        return new Route(a, b, null);
    }

    /**
     * A route that may only be travelled toward the given side.
     */
    private static Route into(Side toward, Side from)
    {
        return new Route(from, toward, toward);
    }

    /**
     * A single open port - a dead end, or the visible side of a portal tile.
     */
    private static Route stub(Side side)
    {
        return new Route(side, side, null);
    }

    private static Map<AccessorySlot, accessorySetting> commands(accessorySetting primary)
    {
        Map<AccessorySlot, accessorySetting> map = new HashMap<>();
        map.put(AccessorySlot.PRIMARY, primary);
        return map;
    }

    private static Map<AccessorySlot, accessorySetting> commands(accessorySetting primary, accessorySetting secondary)
    {
        Map<AccessorySlot, accessorySetting> map = new HashMap<>();
        map.put(AccessorySlot.PRIMARY, primary);
        map.put(AccessorySlot.SECONDARY, secondary);
        return map;
    }

    private static TileState state(Map<AccessorySlot, accessorySetting> commands, Route... routes)
    {
        List<Route> list = new ArrayList<>();
        Collections.addAll(list, routes);
        return new TileState(list, commands);
    }

    /**
     * A fixed tile that nonetheless requires an accessory setting to be passed - a signal.
     */
    private static void signalled(componentType type, accessorySetting setting, Route... routes)
    {
        List<Route> list = new ArrayList<>();
        Collections.addAll(list, routes);

        List<TileState> states = new ArrayList<>();
        states.add(new TileState(list, commands(setting)));

        PORTS.put(type, Collections.unmodifiableList(states));
    }

    private static void fixed(componentType type, Route... routes)
    {
        List<Route> list = new ArrayList<>();
        Collections.addAll(list, routes);

        List<TileState> states = new ArrayList<>();
        states.add(new TileState(list, Collections.<AccessorySlot, accessorySetting>emptyMap()));

        PORTS.put(type, Collections.unmodifiableList(states));
    }

    private static void switched(componentType type, TileState... tileStates)
    {
        List<TileState> states = new ArrayList<>();
        Collections.addAll(states, tileStates);

        PORTS.put(type, Collections.unmodifiableList(states));
    }
}
