#!/bin/bash
#
# Runs every test class, one JVM each, and reports which ones are not green.
#
# Lived in a session scratch directory until 2026-08-25, which is why the bug below could be made
# twice: a harness nobody can read is a harness nobody can review. It is here now.
#
# Usage, from the project root:
#
#     TC_SCRATCH=/path/to/scratch bash docs/tools/battery.sh
#
# DO NOT EDIT THIS FILE WHILE A RUN IS IN PROGRESS. Bash reads a script lazily, by byte offset, so an
# edit above the point it has reached shifts everything after it and the next read lands mid-token.
# The run may carry on looking healthy and produce a result that means nothing. If you need to change
# it during a long run, copy it first and run the copy - which is what a session on 2026-08-25 ended
# up doing, after editing it under a run and having to throw the run away.
#
# TC_SCRATCH holds cp.txt (the classpath, one line) and receives the TestNG output. See
# docs/manual-tests/README.md for how it is built.

set -u

S="${TC_SCRATCH:-}"

if [ -z "$S" ] || [ ! -f "$S/cp.txt" ]
then
    echo "TC_SCRATCH must name a directory containing cp.txt (the classpath)." >&2
    exit 2
fi

# NOT a stale compile directory first.  A leftover tree once shadowed the real one, so the battery
# silently tested old code and a method added minutes earlier came back as NoSuchMethodError.
CP="$(cat "$S/cp.txt")"

# AND THE BATTERY COMPILES THE WORKING TREE ITSELF, which is the other half of that sentence and was
# missing for as long as the sentence has been there.
#
# cp.txt begins with one.sh's output directory, and this script had no compile step of its own - so a
# battery reported on whatever one.sh happened to have compiled last, which is not the same thing as
# the working tree and on 2026-08-29 was not even close.  A mutation had been compiled into that
# directory to prove a test could catch it; the source was restored, the battery was run, and it
# reported the mutation's three failures against a tree that did not contain it.  Every earlier
# battery today was only as true as the last one.sh before it.
#
# The comment above was written about a stale directory SHADOWING the real one.  The failure it did
# not name is the same directory being the ONLY one, which is worse, because then there is nothing to
# shadow and no symptom to notice.
#
# Compiled into a directory of this script's own and PREPENDED, so every class the run loads is one
# this compile produced and one.sh's output cannot reach the classpath ahead of it.
#
# ONE BATTERY AT A TIME, and the directory belongs to the run.
#
# On 2026-08-29 I started a battery while another was still going. They compiled into the same fixed
# directory, so each one's `rm -rf` deleted the other's classes underneath it, and the run came back
# with twenty-seven classes reported as DID NOT RUN. Nothing was wrong with the code.
#
# That is the third defect in this harness to report a FALSE RESULT rather than an error, and they all
# have the same shape: the runner decided what a run meant while something else was changing what it
# was running.
#
# The lock is the fix - the second battery now refuses to start and says which process is already
# going. The per-run directory is the belt: if two ever do overlap despite it, a stale lock or a killed
# run, they no longer compile over each other, and the failure is slow rather than wrong.
# USER-WIDE, NOT PER-SESSION (SV2-A2).
#
# This was "$S/battery.lock", and $S is TC_SCRATCH - a directory per agent session.  So two sessions
# took two different lock files, neither ever looked at the other, and the lock could not have
# prevented a single one of the overlaps it was written for.  Every liveness fix applied to it on
# 2026-09-01 was work on the wrong mechanism.
#
# The crash dumps in the repository root are the evidence: battery-40080 ran out of
# .../0362837d-.../scratchpad/tc and battery-32945 out of .../51b92044-.../scratchpad, and they died
# seconds apart inside the same window.  Four different session ids appear across those files.
#
# TEMP is the same directory for every session of the same user, which is the scope the hazard has -
# the Java Preferences store these runs fight over is per user, not per session.  TC_LOCK overrides it
# for anyone who needs to.
LOCK="${TC_LOCK:-${TEMP:-${TMP:-/tmp}}/traincontrol-battery.lock}"

# THE LOCK IS A PROXY.  THE TEST JVMS ARE THE HAZARD (2026-09-01).
#
# On 2026-09-01 two batteries ran at once anyway, with the lock in place and working as written.  The
# reason is the liveness test below: it refuses only when `kill -0` SUCCEEDS, so every answer that is
# not a clear yes - a pid held by a different shell session, a recycled pid, anything MSYS cannot see
# across process trees - falls through and starts a second run.  A guard that fails open on the
# dangerous side is not a guard, and this one failed open in exactly the case it exists for.
#
# So the pid is no longer the only question.  What is actually dangerous is a second set of test JVMs -
# they share the Java Preferences store, which is what LayoutSandbox redirects, and two runs redirecting
# it at once is how the operator's real railway was damaged on 2026-08-30.  That is a thing this script
# can LOOK FOR rather than infer, and it is true whether the other run came from a battery, from one.sh,
# from an IDE, or from somebody else's session entirely - none of which the lock can see.
#
# It also needs no clearing by hand, which is the property the comment above insists on: the check
# stops being true the moment the other JVMs exit.  Nobody has to delete anything to get past it, so
# nobody learns to delete things to get past it.
#
# IT LOOKS FOR TestNG, NOT FOR OUR OWN FLAG (SVN-A2, corrected the same day it was written).
#
# The first version matched `-Dtraincontrol.anyReceivePort`, which is a flag only this script and
# one.sh set - so it saw its own family and nothing else, while its comment claimed it caught an IDE
# run too.  `build.xml` passes no `jvmarg` at all: an `ant test` or a NetBeans run was exactly as
# invisible as before.  What every one of them does have in common is the runner itself, so that is
# what is matched, and the old flag is kept as well for anything that sets it without TestNG on the
# command line.
#
# Adam's own running application is deliberately NOT matched.  It is not a test JVM, it does not
# redirect the preference, and blocking every battery while he has the app open would be the kind of
# over-strict guard that gets deleted rather than obeyed.
# javac too (SV2-A2): a battery owns no JVM at all while it is compiling, which is precisely
# where the two runs of 2026-09-01 overlapped - both of them in javac.  Measured on this
# machine the javac process itself lives only a few seconds, not the "minute or two" an
# earlier version of this comment claimed; short is not the same as absent, and two runs
# started together land in it together.
#
# MATCHED BY THE ARGFILE, not by the project name (TV2-C1).  The first version of this asked
# for a javac whose command line contains "TrainControl", and neither runner's compile has
# that on it when cp.txt holds relative paths - which this session's does.  The measurement
# that "confirmed" it was matching the testng clause instead.  What IS always present is the
# argfile: one-files.txt or battery-files.txt.
PROBE="(Get-CimInstance Win32_Process -Filter \"Name='java.exe' OR Name='javac.exe'\" | Where-Object { \$_.CommandLine -like '*anyReceivePort*' -or \$_.CommandLine -like '*testng*' -or \$_.CommandLine -like '*TestNG*' -or \$_.CommandLine -like '*one-files*' -or \$_.CommandLine -like '*battery-files*' } | Measure-Object).Count"

RUNNING_JVMS=$(powershell.exe -NoProfile -Command "$PROBE" 2>/dev/null | tr -d '\r\n ')

# The arms test the WHOLE answer, not its first character (FV2-C5).  "12abc" matched [0-9]* here, the
# -gt then failed with its diagnostic going to /dev/null, and the run proceeded without the warning this
# very case exists for - the malformed half of the thing the warning was added for.
case "$RUNNING_JVMS" in
    ''|*[!0-9]*)
        # SAID OUT LOUD RATHER THAN SWALLOWED.  The probe failing and the probe answering "none" used
        # to be the same silence, so a broken check read exactly like a clear one - which is the shape
        # of every false result this harness has produced.  The run still goes ahead, because a guard
        # that stops all work when its own probe breaks is worse than the hazard, and the lock below
        # is still standing; but nobody reads this output believing the check ran.
        echo "*** WARNING: could not count running test JVMs - this check DID NOT RUN ***"
        echo ""
        echo "PowerShell returned: '$RUNNING_JVMS'.  Make sure nothing else is running tests."
        echo ""
        ;;
    *)
        if [ "$RUNNING_JVMS" -gt 0 ]
        then
            echo "*** TEST JVMS ARE ALREADY RUNNING ($RUNNING_JVMS of them) ***"
            echo ""
            echo "Something else is running tests right now - another battery, a one.sh, an ant run,"
            echo "or the IDE.  Test JVMs share the Java Preferences store that LayoutSandbox"
            echo "redirects, and two runs redirecting it at once is how the real railway was damaged"
            echo "on 2026-08-30."
            echo ""
            echo "Wait for it to finish, or stop it, and run this again.  Nothing needs deleting:"
            echo "this check clears itself when those processes exit."
            exit 2
        fi
        ;;
esac

# AND THE LOCK IS WHAT COVERS THE COMPILE.
#
# The JVM check above cannot see a battery that has not reached its JVMs yet, and this script compiles
# the whole tree first - a minute or more in which a second run looks past it and finds nothing.  That
# is exactly the window the two concurrent batteries of 2026-09-01 overlapped in: both were in javac,
# so neither could see the other by its processes.  The lock is held from here, before the compile, so
# it is the only thing that covers that window - which makes its liveness test worth getting right.
#
# `kill -0` was the wrong test.  MSYS resolves pids within its own process tree, so a lock written by
# a shell in another session reads as dead, the guard concludes "stale" and starts a second run.  It
# has to fail open on every answer that is not a clear yes, which is the dangerous direction.
#
# Windows can answer the question that MSYS cannot, so it is asked instead - and the three outcomes are
# now distinguished rather than collapsed into two: alive refuses, dead proceeds quietly, and an
# unanswerable probe says so and proceeds, because a battery nobody can run is worse than this hazard
# and the guard above is still standing.
# AND THE LOCK MUST HOLD A PID WINDOWS HAS HEARD OF (FV2-A1, corrected within hours).
#
# The first version of this asked `Get-Process -Id` about `$$`, which is the MSYS pid - a number
# Windows does not use.  Measured on this machine: a live shell is msys 42457 / winpid 17552, and
# `Get-Process -Id 42457` answers "no" while `-Id 17552` answers "yes".  So every LIVE battery read as
# stale, the script announced "clearing a stale lock" and started a second run inside the compile
# window the lock exists to cover.  It was strictly worse than the `kill -0` it replaced.
#
# It passed its test because the test wrote a Windows pid into the lock by hand and watched the check
# refuse.  That exercised the branch with a value the script never writes - the check was verified and
# the integration was not.
#
# So the lock holds the winpid now, and liveness is "either test says alive": Get-Process for the
# Windows number, and kill -0 as well, which does work across MSYS sessions - the earlier claim that
# it does not was also wrong.  Two tests that can only ever say "still running" cannot combine into a
# false "stale", which is the only direction that costs anything here.
LOCK_PID=$(cat /proc/$$/winpid 2>/dev/null | tr -d '\r\n ')

# THE NAMESPACE, WRITTEN WITH THE NUMBER (SV2-C2).
#
# The fallback wrote a bare MSYS pid, and a reader cannot tell which space a bare integer is in.
# `Get-Process` is guaranteed to answer "no" about an MSYS pid - measured - so such a lock was
# resolvable only by `kill -0`, and where that cannot answer either (a different MSYS installation,
# WSL, an EPERM) both readers say no, the lock reads STALE, and a LIVE battery's lock is cleared.  That
# is FV2-A1's failure mode surviving in the one branch nobody exercised.
case "$LOCK_PID" in
    ''|*[!0-9]*) LOCK_PID="msys:$$" ;;
esac

STALE=""

# INITIALISED, like STALE above it, and for the reason that one was (TSX-B7).
#
# `ALIVE` is assigned only inside the `if [ -f "$LOCK" ]` block below, and read again after it - so on
# every machine with no lock file, which is every machine after any run that ended normally, `set -u`
# killed the script with "ALIVE: unbound variable" before it compiled anything.  Exit 1 is this
# script's own code for "classes with failures", so a caller chaining on it was told the tests failed
# by a run that never started.
#
# Introduced by REL-C10's fix this morning: `one.sh` was RESTRUCTURED and this file was patched in
# place, which is why the claim that the two takes are "word for word the same" was not true - and the
# one that missed the restructure is the one that broke.
ALIVE=""

# TESTED AND TAKEN AS ONE STEP, further down (SV2-C3).
#
# What follows READS the lock, and the write used to be a plain `echo >` a few lines later - so two
# batteries launched together both found no file, both wrote, and both proceeded.  It needs sub-second
# simultaneity, which is exactly what two runs started by the same script have.
#
# The creation below uses `set -o noclobber`, which makes "create it only if it does not exist" one
# operation the filesystem decides rather than two this script decides.  This read stays: it is what
# produces the message, and what clears a lock whose holder is gone.
if [ -f "$LOCK" ]
then
    HELD=$(cat "$LOCK" 2>/dev/null | tr -d '\r\n ')

    # EACH NUMBER ASKED OF THE TOOL THAT CAN ANSWER IT (SV2-C2).
    #
    # A winpid is a bare integer and Windows can resolve it.  An MSYS pid is written "msys:NNN" and
    # only `kill -0` can, and only from a shell in the same MSYS runtime - so asking Windows about one
    # returns "no" for the wrong reason, which is how a live battery's lock came to be cleared.
    case "$HELD" in
        msys:*)
            HELD_MSYS=${HELD#msys:}
            HELD_WIN=""
            ;;
        *)
            HELD_MSYS="$HELD"
            HELD_WIN="$HELD"
            ;;
    esac

    ALIVE="unknown"

    if [ -n "$HELD_WIN" ]
    then
        ALIVE=$(powershell.exe -NoProfile -Command \
            "if (Get-Process -Id $HELD_WIN -ErrorAction SilentlyContinue) { 'yes' } else { 'no' }" \
            2>/dev/null | tr -d '\r\n ')
    fi

    # The second opinion, for a lock written before this change or by a shell with no /proc.  Only ever
    # ADDS a "yes": two tests that can say "still running" cannot combine into a false "stale", which is
    # the only direction that costs anything here.
    if [ "$ALIVE" != "yes" ] && [ -n "$HELD_MSYS" ] && kill -0 "$HELD_MSYS" 2>/dev/null
    then
        ALIVE="yes"
    fi

    # An MSYS lock that `kill -0` could not resolve is UNKNOWN rather than dead: this shell may simply
    # be a different MSYS runtime.  The unknown arm warns and proceeds, which is what it is for.
    if [ "$ALIVE" != "yes" ] && [ -z "$HELD_WIN" ]
    then
        ALIVE="unknown"
    fi

    case "$ALIVE" in
        yes)
            echo "*** ANOTHER BATTERY IS ALREADY RUNNING (pid $HELD) ***"
            echo ""
            echo "Two at once compile over each other and report classes that ran perfectly well as"
            echo "DID NOT RUN.  Wait for it, or stop it, and run this again."
            exit 2
            ;;
        no)
            STALE="$HELD"
            ;;
        *)
            echo "*** WARNING: could not tell whether the battery holding this lock (pid $HELD) is"
            echo "    still running - that check DID NOT RUN.  Make sure no other battery is going."
            echo ""
            ;;
    esac
fi


# TAKEN, OR TAKEN OVER, IN ONE STEP (SV2-C3, corrected by REL-C9 and REL-C10).
#
# `set -o noclobber` with `: >` makes "create it only if it does not exist" one operation the
# filesystem decides, rather than two this script decides with a `powershell.exe` start between them -
# which is the few hundred milliseconds two runs launched together spend in parallel.
#
# **A lock nobody owns is taken OVER, not deleted and re-created.**  The first version of this did
# `rm -f` and then created, which is two steps again: two shells racing past the same stale lock could
# interleave rm-A, create-A, rm-B, create-B and both proceed (REL-C9).  `mv` is one operation, so
# exactly one of them wins it.
#
# **And the unknown arm still warns and proceeds** (REL-C10).  A lock whose number nobody can resolve
# is possibly days old; refusing would leave deleting the file by hand as the only way past, which is
# the learned behaviour the probe's own comment forbids.
#
# The pid goes through a temp file, so the lock is never present and empty for a reader to find.
take_the_lock()
{
    if ( set -o noclobber; : > "$LOCK" ) 2>/dev/null
    then
        printf "%s\n" "$LOCK_PID" > "$LOCK.mine.$$" && mv -f "$LOCK.mine.$$" "$LOCK"

        return 0
    fi

    return 1
}

if [ -n "$STALE" ]
then
    echo "(clearing a stale lock from pid $STALE, which is no longer running)"
    echo ""

    mv "$LOCK" "$LOCK.stale.$$" 2>/dev/null && rm -f "$LOCK.stale.$$"
fi

if [ "$ALIVE" = "unknown" ] && [ -f "$LOCK" ]
then
    mv "$LOCK" "$LOCK.stale.$$" 2>/dev/null && rm -f "$LOCK.stale.$$"
fi

if ! take_the_lock
then
    echo "*** ANOTHER RUN TOOK THE LOCK IN THE SAME INSTANT - nothing was run ***"
    echo ""
    echo "Two started within a few milliseconds of each other.  Wait for the other one and try again."
    echo ""

    exit 2
fi

BUILD="$S/build/battery-$$"

# The lock and this run's classes go whichever way the script leaves - including the live-layout
# guard's exit 1, which is the one somebody is most likely to be reading when it fires, and including
# being killed.
#
# INT and TERM as well as EXIT, because a battery is usually stopped rather than waited for, and a run
# that is killed without releasing its lock blocks every later one - a guard that has to be cleared by
# hand is worse than no guard, because the first thing anybody does is delete the lock and stop
# believing in it.
# ------------------------------------------------------------------------------------------------
# ON THE WAY OUT, WHICHEVER WAY (TSX-C14).
#
# Three things the traps did not do, all of which matter most on the path they are for - a run that
# was stopped rather than waited for.
#
# THE LOCK IS RELEASED ONLY IF IT IS STILL OURS.  `rm -f "$LOCK"` never asked.  Since REL-C10 the
# unknown arm deliberately takes a live-but-unresolvable lock OVER, so two runs holding the "same"
# lock is a state this is designed for - and the first of them to finish was deleting the second's
# lock and leaving the machine unlocked with a battery still going.  REL-C9 named this sequence for
# the `mv` and the trap was not changed with it.
#
# THE REAPER RUNS.  A run stopped part way leaves the class it was on going, and reap.ps1 matches the
# run id whole while that id embeds this shell's pid - so once the shell is gone nothing can ever
# match it again.  That is the permanence argument battery.sh already writes out for its post-loop
# reap, arriving at the trap.
#
# AND THE LAYOUT IS CHECKED.  one.sh's own header states the rule: "a guard that only runs on the
# slow path is a guard that is not running."  The run most likely to have written to
# cs2_sample_layout is the one that was killed because a class hung, and that was the one run neither
# script looked at.  Only when the run did NOT reach its own report, which does this properly.
release_the_lock()
{
    if [ "$(cat "${LOCK:-}" 2>/dev/null | tr -d '\r\n ')" = "${LOCK_PID:-}" ]
    then
        rm -f "${LOCK:-}"
    fi
}

REPORTED=""

# ONCE, NOT TWICE (VD9-B2).
#
# `trap '...; exit 130' INT TERM` runs its body and then exits - and exiting fires the EXIT trap,
# which runs the same body again.  Measured, not assumed: a throwaway script with this exact pair
# prints its handler twice.  So a killed run reaped twice and, worse, printed the "this run was
# stopped and the layout changed" warning twice, which reads as two events.
DONE=""

on_the_way_out()
{
    if [ -n "${DONE:-}" ]; then return; fi

    DONE=1

    # BEFORE the fingerprint, because a leftover JVM is by definition one that is still running and
    # deferred work landing after everybody stopped watching is the whole subject of LayoutSandbox.
    #
    # Written out rather than calling reap(), and every variable defaulted - genuinely every one
    # now (VD9-C7): $LOCK, $REPORTED and $DONE were not, and under `set -u` an unbound one aborts
    # the trap at that line and takes `rm -rf "$BUILD"` with it, which is the exact failure this
    # comment claimed to be preventing.
    #
    # It could not happen, because all three are set before the trap is armed - but that is safety
    # by arming order, and this body is meant to survive being moved.
    if [ -n "${REAPER:-}" ]
    then
        powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$REAPER"             -RunId "${RUN_ID:-}" >/dev/null 2>&1
    fi

    if [ -z "${REPORTED:-}" ] && [ -n "${live_before:-}" ]
    then
        if [ "$live_before" != "$(fingerprint)" ]
        then
            echo ""
            echo "*** THIS RUN WAS STOPPED, AND ${LIVE:-the layout} CHANGED WHILE IT RAN ***"
            echo ""
            echo "That folder is Adam's real railway.  Check it before trusting anything above, and"
            echo "check whether TrainControl was open - a running railway rewrites it as trains move."
            echo ""
        fi
    fi

    release_the_lock

    rm -rf "${BUILD:-}"
}

trap 'on_the_way_out; exit 130' INT TERM
trap 'on_the_way_out' EXIT

rm -rf "$BUILD"
mkdir -p "$BUILD"

find src test -name "*.java" > "$S/battery-files.txt"

if ! "${TC_JAVAC:-/c/Program Files/Java/jdk1.8.0_361/bin/javac}" -nowarn -encoding UTF-8 \
    -d "$BUILD" -cp "$CP" @"$S/battery-files.txt" 2>"$S/battery-javac.log"
then
    echo "*** THE WORKING TREE DOES NOT COMPILE - nothing was run ***"
    echo ""
    grep -i "error" "$S/battery-javac.log" | head -20
    exit 2
fi

CP="$BUILD;$CP"

JAVA="${TC_JAVA:-/c/Program Files/Java/jdk1.8.0_361/bin/java}"

# Any free receive port instead of the Marklin one.
#
# Every class that builds a MarklinControlStation used to bind UDP 15730, so the battery could not run
# while TrainControl was open, an orphaned JVM poisoned every class after it, and two classes could
# never overlap. None of them receives anything from a Central Station - there is none - so the port
# was pure contention.
#
# The failure it removes is a nasty one to read: a bind failure comes out of @BeforeClass as
# "Total tests run: 16, Failures: 0, Skips: 16" - zero failures, having tested nothing.
JAVA_FLAGS="${TC_JAVA_FLAGS:--Dtraincontrol.anyReceivePort=true}"

# This run's own name, so the reaper can tell this battery's leftovers from anything else on the
# machine - including another battery, and including a test somebody is running by hand.
#
# Without it the reaper matched every JVM carrying the receive-port flag, which is every test JVM
# there is: a battery running in the background killed a hand-run test at exit 127 with no output,
# which reads as the test hanging rather than as something else shooting it.
RUN_ID="battery-$$"

# WHERE THE REAPER IS, resolved once and checked (TS3-A1).
#
# Said out loud rather than swallowed: a reaper that is not there is exactly the condition that let
# four days of runs leave their JVMs behind, and the whole reason it went unnoticed is that the call
# could not fail visibly.  A run without one is still worth having, so this warns rather than refuses.
REAPER="$(cd "$(dirname "$0")" && pwd)/reap.ps1"

if [ ! -f "$REAPER" ]
then
    echo "*** WARNING: no reaper at $REAPER - leftover test JVMs will NOT be cleaned up ***"
    echo ""
    echo "A JVM left behind by one class poisons every class after it, and trips the next run's"
    echo "start-of-run probe with a message that says the check clears itself.  It will not."
    echo ""

    REAPER=""
fi

JAVA_FLAGS="$JAVA_FLAGS -Dtraincontrol.batteryRun=$RUN_ID"

# A BOUNDED HEAP, because an unbounded one asks for a quarter of the machine per class.
#
# A default-heap JVM reserves a fraction of physical RAM up front. With NetBeans open and Adam running
# his own tests, three classes in battery34 could not get it, died before TestNG loaded, and were
# reported as DID NOT RUN - the same wording as a class that crashed, so the run looked like it had
# three faults in it and had none. All three pass in 512m, and the heaviest class here peaks nowhere
# near that.
#
# Overridable, because the number is a guess about this machine rather than a property of the tests.
JAVA_FLAGS="$JAVA_FLAGS ${TC_JAVA_HEAP:--Xmx512m}"

# Adam's own railway, hashed before and after the whole run.
#
# A test class can watch its OWN writes - testTheGoldenLayoutHoldsTogether does - but not
# another class's, and the write that actually happened came from a class that had no idea it
# was near his layout: two of them start the real window, which opens whatever the saved UI
# state names.
#
# It went unnoticed for two days.  This is the scope that would have caught it on the first run.
LIVE="cs2_sample_layout"

fingerprint()
{
    if [ -d "$LIVE" ]
    then
        # Carriage returns stripped before hashing.
        #
        # Git checks these files out with CRLF and the application writes them with LF, so a
        # file rewritten with identical content still differs byte for byte.  Reporting that
        # would make this guard fire on every run, and a guard that always fires is one nobody
        # reads - which is the failure this whole check exists to prevent, arriving from the
        # other side.
        find "$LIVE" -type f -print0 2>/dev/null | sort -z | while IFS= read -r -d "" f
        do
            printf "%s  %s\n" "$(tr -d "\r" < "$f" | sha256sum | cut -d" " -f1)" "$f"
        done
    fi
}

live_before=$(fingerprint)

pass=0
fail=0
skip=0
failed=""
skipped=""

for f in $(find test -name "*.java" | sort)
do
    cls=$(echo "$f" | sed 's|^test/||; s|\.java$||; s|/|.|g')

    case "$cls" in *.*) ;; *) continue;; esac

    # Skipped for the reason build.xml gives: it "probes the network for a real Central Station at a
    # hardcoded address" and blocks until that answers. It hung this runner for fourteen minutes.
    case "$cls" in *testAutoDetect) echo "SKIP $cls (needs a Central Station)"; continue;; esac

    # THE HELPERS ARE NOT TESTS, and counting them taught the reader to ignore the line.
    #
    # `support/` holds CS3TestServer, LayoutSandbox and TestStationAddress - a fake station, the
    # preference redirect that keeps tests off Adam's railway, and an address helper.  None has a
    # @Test, so every run ended "classes that tested nothing: 3" and that number was never zero.
    #
    # A count that is always three is not a signal.  The check exists to catch a class whose
    # @BeforeClass threw - which reports every test skipped and none failed - and a reader who has
    # learned that the last line always says three will not see the four.  `build.xml` already says
    # TestStationAddress is "a helper rather than a test"; this is the same statement, made where the
    # counting happens.
    case "$cls" in support.*) continue;; esac

    # Only THIS RUN's leftover JVMs - reap.ps1 says why that is narrower than "every test JVM", and
    # narrower again than "every java.exe".
    #
    # FROM THE SCRIPT'S OWN DIRECTORY, not from the working directory (TS3-A1).
    #
    # This read "$(pwd)/tools/reap.ps1" from 2026-08-25 until 2026-09-02, and the file has been at
    # docs/tools/reap.ps1 since fb3722f5 moved the folder on 2026-08-30 - a commit whose message says
    # "all eleven referring files repointed" and which missed this one, the script's call to its own
    # sibling.  With the error going to /dev/null, every battery for four days reaped nothing and said
    # nothing about it.
    if [ -n "$REAPER" ]
    then
        powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$REAPER" \
            -RunId "$RUN_ID" >/dev/null 2>&1
    fi

    # The WHOLE output, not its last few lines (found 2026-08-25).
    #
    # This was `| tail -4`, and it turned a green class into "DID NOT RUN". TestNG prints its summary
    # and then anything the JVM still has to say - and core.testAutonomySimulationSanity ends with a
    # Marklin packet dump from a socket timing out, so the summary had scrolled past by line four.
    #
    # That is the third harness defect in this round that reported a false result rather than an
    # error, and they all have the same shape: the runner decided what a run meant by looking at part
    # of it. It is cheap to read all of it.
    out=$("$JAVA" $JAVA_FLAGS -cp "$CP" org.testng.TestNG -testclass "$cls" -d "$S/tng-run/$cls" 2>&1)

    # The LAST one, because a class can print the word before it finishes - and the last summary is
    # the one that describes the whole run.
    summary=$(echo "$out" | grep 'Total tests run' | tail -1)

    # TestNG's summary is TWO lines, and this read one (found 2026-08-25, by review).
    #
    #     Total tests run: 1, Failures: 0, Skips: 0
    #     Configuration Failures: 1, Skips: 0
    #
    # A class whose @AfterClass throws prints exactly that, and the first line alone says green.  The
    # teardowns in this suite are load-bearing: testBothProtectingSignalsAreThrown puts two of Adam's
    # real signals back to GREEN in its teardown and says why, and testARouteDoesNotThrowSwitchesUnderATrain
    # clears the auto layout in its own.  A teardown that threw would leave the railway changed and be
    # reported as a clean run.
    configFailures=$(echo "$out" | grep 'Configuration Failures' | tail -1)

    if [ -z "$summary" ]
    then
        # A class that produced no summary did not run.  Reported as a failure on purpose: a runner
        # that reads only "Failures:" calls a class that never started clean.
        # SAY WHICH KIND, because the two need opposite responses.  A JVM that could not reserve
        # its heap is the machine being busy, and the answer is to run it again; anything else is the
        # class, and the answer is to go and read it.  They read identically before this, which cost a
        # round of hunting for a fault in three classes that were fine.
        # BOTH WORDINGS, and neither is the one this first grepped for.  A 64-bit JDK 8 says
        # "Unable to allocate NNN bitmaps ... for the requested NNNKB heap" when -Xmx cannot be met,
        # and its other reservation message embeds the size - "Could not reserve enough space for
        # %I64uKB object heap" - so matching the bare sentence matched neither, and the branch was
        # dead for the very incident it was written for.
        if echo "$out" | grep -qE "Could not reserve enough space|Unable to allocate.*heap"
        then
            fail=$((fail+1)); failed="$failed\n  $cls: DID NOT RUN - no heap (machine busy, rerun)"
        else
            fail=$((fail+1)); failed="$failed\n  $cls: DID NOT RUN"
        fi

    elif ! echo "$summary" | grep -q "Failures: 0"
    then
        fail=$((fail+1)); failed="$failed\n  $cls: $summary"

    elif [ -n "$configFailures" ] && ! echo "$configFailures" | grep -q "Configuration Failures: 0"
    then
        fail=$((fail+1)); failed="$failed\n  $cls: $summary / $configFailures"

    elif echo "$summary" | grep -q "Total tests run: 0"
    then
        # ZERO tests is not zero failures (found 2026-08-25, by review).
        #
        # The skip fix below catches "Skips: N".  A class that discovers no tests at all prints
        # "Total tests run: 0, Failures: 0, Skips: 0", which satisfies both of those and landed in the
        # pass branch - so support/CS3TestServer.java and support/TestStationAddress.java, which hold
        # no tests, were counted among the green on every run.  The number was inflated by two.
        #
        # The same shape catches a class that has lost its @Test annotations, or was disabled for
        # debugging and never restored.  Counted with the skips rather than as a failure, for the same
        # reason: it needs looking at, not alarming about.
        skip=$((skip+1)); skipped="$skipped\n  $cls: $summary (no tests in this class)"

    elif echo "$summary" | grep -q "Skips: 0"
    then
        pass=$((pass+1))

    else
        # GREEN IS NOT "no failures" (found 2026-08-25).
        #
        # A class whose @BeforeClass throws reports every one of its tests as SKIPPED and none as
        # failed, so "Failures: 0" was true of a class that had tested nothing at all.
        # core.testAutonomyDiagramSampleLayout sat like that - 13 tests, 0 passed, 13 skipped -
        # and every battery in this session counted it among the green.  The stale coordinate that
        # broke it went in with the fixture separation and nothing said a word for two days.
        #
        # Counted apart rather than as a failure, because a skip can be legitimate: several
        # classes need a display and say so.  The point is that it must not read as "fine".
        skip=$((skip+1)); skipped="$skipped\n  $cls: $summary"
    fi
done

# THE REAP FIRST, THEN THE FINGERPRINT (TSX-C14).
#
# These were the other way round, and one.sh has always had them this way.  A leftover JVM is by
# definition one that is still running: taking the hash while it is alive and then killing it makes
# a write it manages in between invisible, and the run reports the folder untouched.  Deferred work
# landing after everybody stopped watching is the whole subject of LayoutSandbox's javadoc.
if [ -n "$REAPER" ]
then
    powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$REAPER" \
        -RunId "$RUN_ID" >/dev/null 2>&1
fi

live_after=$(fingerprint)

# THE TRAP'S COPY OF THIS CHECK STANDS DOWN NOW (TSX-C14).
#
# What follows reports the comparison properly, with the diff and the question about whether
# TrainControl was open.  The trap's version exists for the run that never gets here.
REPORTED=1

# AND AFTER THE LAST CLASS (V33-C1).
#
# The reap above runs at the TOP of the loop, so every class is cleaned up before the next one starts
# and the last one is not cleaned up at all.  A run that ends on a class which left a JVM behind
# therefore leaves it behind for good - and the next run's start-of-run probe refuses to start, with a
# message saying the check clears itself.
#
# The most likely class to do it is the last one alphabetically rather than a bad one, which is what
# makes this hard to notice: it is not a symptom of anything being wrong.
if [ -n "$REAPER" ]
then
    powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$REAPER" \
        -RunId "$RUN_ID" >/dev/null 2>&1
fi

echo "classes green: $pass   classes with failures: $fail   classes that tested nothing: $skip"
echo -e "$failed"

if [ "$skip" -gt 0 ]
then
    echo ""
    echo "These classes reported no failures because they ran nothing.  A skipped class is not a"
    echo "green class - check whether the skip is deliberate (needing a display) or a broken setup:"
    echo -e "$skipped"
fi

if [ "$live_before" != "$live_after" ]
then
    echo ""
    echo "*** THE TEST SUITE WROTE TO $LIVE ***"
    echo ""
    echo "That folder is Adam's real railway and holds his accumulated autonomy setup, which is"
    echo "not recoverable.  Find the class that did it before trusting anything above."
    echo ""
    echo "BUT FIRST: was TrainControl open while this ran?  The application writes to that folder"
    echo "too - every train that moves rewrites its placement - and this check hashes the folder"
    echo "before and after the whole run, so it cannot tell the two apart.  Changes to 'loc' and"
    echo "'facing' in configuration-*.json are what a running railway looks like; changes to"
    echo "setup.json, or a file appearing or disappearing, are not.  Look at the diff before"
    echo "hunting for a class."
    echo ""
    diff <(echo "$live_before") <(echo "$live_after") | grep '^[<>]' | sed 's/^/  /'
fi

# And an EXIT CODE, so this can be read by something other than a person.
#
# The script reported failures as text and exited on whatever the last `if` happened to leave behind,
# which is success.  Nothing reads it that way today - it is read by eye - so this costs nothing now
# and stops being a trap the first time somebody puts it behind `&&` or in CI, which is exactly when
# nobody would be watching the text.
#
# A class that tested nothing counts.  It is not a failure, but it is not a pass either, and a caller
# asking "was this run good" is asking about both.  The text above distinguishes them; the code does
# not have to.
if [ "$fail" -gt 0 ] || [ "$live_before" != "$live_after" ]
then
    exit 1
fi

if [ "$skip" -gt 0 ]
then
    exit 2
fi

exit 0
