#!/bin/bash
#
# Runs every test class, one JVM each, and reports which ones are not green.
#
# Lived in a session scratch directory until 2026-08-25, which is why the bug below could be made
# twice: a harness nobody can read is a harness nobody can review. It is here now.
#
# Usage, from the project root:
#
#     TC_SCRATCH=/path/to/scratch bash docs/tools/battery.sh
#
# DO NOT EDIT THIS FILE WHILE A RUN IS IN PROGRESS. Bash reads a script lazily, by byte offset, so an
# edit above the point it has reached shifts everything after it and the next read lands mid-token.
# The run may carry on looking healthy and produce a result that means nothing. If you need to change
# it during a long run, copy it first and run the copy - which is what a session on 2026-08-25 ended
# up doing, after editing it under a run and having to throw the run away.
#
# TC_SCRATCH holds cp.txt (the classpath, one line) and receives the TestNG output. See
# docs/manual-tests/README.md for how it is built.

set -u

S="${TC_SCRATCH:-}"

if [ -z "$S" ] || [ ! -f "$S/cp.txt" ]
then
    echo "TC_SCRATCH must name a directory containing cp.txt (the classpath)." >&2
    exit 2
fi

# NOT a stale compile directory first.  A leftover tree once shadowed the real one, so the battery
# silently tested old code and a method added minutes earlier came back as NoSuchMethodError.
CP="$(cat "$S/cp.txt")"

# AND THE BATTERY COMPILES THE WORKING TREE ITSELF, which is the other half of that sentence and was
# missing for as long as the sentence has been there.
#
# cp.txt begins with one.sh's output directory, and this script had no compile step of its own - so a
# battery reported on whatever one.sh happened to have compiled last, which is not the same thing as
# the working tree and on 2026-08-29 was not even close.  A mutation had been compiled into that
# directory to prove a test could catch it; the source was restored, the battery was run, and it
# reported the mutation's three failures against a tree that did not contain it.  Every earlier
# battery today was only as true as the last one.sh before it.
#
# The comment above was written about a stale directory SHADOWING the real one.  The failure it did
# not name is the same directory being the ONLY one, which is worse, because then there is nothing to
# shadow and no symptom to notice.
#
# Compiled into a directory of this script's own and PREPENDED, so every class the run loads is one
# this compile produced and one.sh's output cannot reach the classpath ahead of it.
#
# ONE BATTERY AT A TIME, and the directory belongs to the run.
#
# On 2026-08-29 I started a battery while another was still going. They compiled into the same fixed
# directory, so each one's `rm -rf` deleted the other's classes underneath it, and the run came back
# with twenty-seven classes reported as DID NOT RUN. Nothing was wrong with the code.
#
# That is the third defect in this harness to report a FALSE RESULT rather than an error, and they all
# have the same shape: the runner decided what a run meant while something else was changing what it
# was running.
#
# The lock is the fix - the second battery now refuses to start and says which process is already
# going. The per-run directory is the belt: if two ever do overlap despite it, a stale lock or a killed
# run, they no longer compile over each other, and the failure is slow rather than wrong.
LOCK="$S/battery.lock"

# THE LOCK IS A PROXY.  THE TEST JVMS ARE THE HAZARD (2026-09-01).
#
# On 2026-09-01 two batteries ran at once anyway, with the lock in place and working as written.  The
# reason is the liveness test below: it refuses only when `kill -0` SUCCEEDS, so every answer that is
# not a clear yes - a pid held by a different shell session, a recycled pid, anything MSYS cannot see
# across process trees - falls through and starts a second run.  A guard that fails open on the
# dangerous side is not a guard, and this one failed open in exactly the case it exists for.
#
# So the pid is no longer the only question.  What is actually dangerous is a second set of test JVMs -
# they share the Java Preferences store, which is what LayoutSandbox redirects, and two runs redirecting
# it at once is how the operator's real railway was damaged on 2026-08-30.  That is a thing this script
# can LOOK FOR rather than infer, and it is true whether the other run came from a battery, from one.sh,
# from an IDE, or from somebody else's session entirely - none of which the lock can see.
#
# It also needs no clearing by hand, which is the property the comment above insists on: the check
# stops being true the moment the other JVMs exit.  Nobody has to delete anything to get past it, so
# nobody learns to delete things to get past it.
RUNNING_JVMS=$(powershell.exe -NoProfile -Command \
    "(Get-CimInstance Win32_Process -Filter \"Name='java.exe'\" | Where-Object { \$_.CommandLine -like '*anyReceivePort*' } | Measure-Object).Count" \
    2>/dev/null | tr -d '\r\n ')

case "$RUNNING_JVMS" in
    ''|0|*[!0-9]*) ;;
    *)
        echo "*** TEST JVMS ARE ALREADY RUNNING ($RUNNING_JVMS of them) ***"
        echo ""
        echo "Something else is running tests right now - another battery, a one.sh, or an IDE."
        echo "Test JVMs share the Java Preferences store that LayoutSandbox redirects, and two runs"
        echo "redirecting it at once is how the real railway was damaged on 2026-08-30."
        echo ""
        echo "Wait for it to finish, or stop it, and run this again.  Nothing needs deleting: this"
        echo "check clears itself when those processes exit."
        exit 2
        ;;
esac

if [ -f "$LOCK" ] && kill -0 "$(cat "$LOCK" 2>/dev/null)" 2>/dev/null
then
    echo "*** ANOTHER BATTERY IS ALREADY RUNNING (pid $(cat "$LOCK")) ***"
    echo ""
    echo "Two at once compile over each other and report classes that ran perfectly well as"
    echo "DID NOT RUN.  Wait for it, or stop it, and run this again."
    exit 2
fi

echo $$ > "$LOCK"

BUILD="$S/build/battery-$$"

# The lock and this run's classes go whichever way the script leaves - including the live-layout
# guard's exit 1, which is the one somebody is most likely to be reading when it fires, and including
# being killed.
#
# INT and TERM as well as EXIT, because a battery is usually stopped rather than waited for, and a run
# that is killed without releasing its lock blocks every later one - a guard that has to be cleared by
# hand is worse than no guard, because the first thing anybody does is delete the lock and stop
# believing in it.
trap 'rm -f "$LOCK"; rm -rf "$BUILD"; exit 130' INT TERM
trap 'rm -f "$LOCK"; rm -rf "$BUILD"' EXIT

rm -rf "$BUILD"
mkdir -p "$BUILD"

find src test -name "*.java" > "$S/battery-files.txt"

if ! "${TC_JAVAC:-/c/Program Files/Java/jdk1.8.0_361/bin/javac}" -nowarn -encoding UTF-8 \
    -d "$BUILD" -cp "$CP" @"$S/battery-files.txt" 2>"$S/battery-javac.log"
then
    echo "*** THE WORKING TREE DOES NOT COMPILE - nothing was run ***"
    echo ""
    grep -i "error" "$S/battery-javac.log" | head -20
    exit 2
fi

CP="$BUILD;$CP"

JAVA="${TC_JAVA:-/c/Program Files/Java/jdk1.8.0_361/bin/java}"

# Any free receive port instead of the Marklin one.
#
# Every class that builds a MarklinControlStation used to bind UDP 15730, so the battery could not run
# while TrainControl was open, an orphaned JVM poisoned every class after it, and two classes could
# never overlap. None of them receives anything from a Central Station - there is none - so the port
# was pure contention.
#
# The failure it removes is a nasty one to read: a bind failure comes out of @BeforeClass as
# "Total tests run: 16, Failures: 0, Skips: 16" - zero failures, having tested nothing.
JAVA_FLAGS="${TC_JAVA_FLAGS:--Dtraincontrol.anyReceivePort=true}"

# This run's own name, so the reaper can tell this battery's leftovers from anything else on the
# machine - including another battery, and including a test somebody is running by hand.
#
# Without it the reaper matched every JVM carrying the receive-port flag, which is every test JVM
# there is: a battery running in the background killed a hand-run test at exit 127 with no output,
# which reads as the test hanging rather than as something else shooting it.
RUN_ID="battery-$$"

JAVA_FLAGS="$JAVA_FLAGS -Dtraincontrol.batteryRun=$RUN_ID"

# A BOUNDED HEAP, because an unbounded one asks for a quarter of the machine per class.
#
# A default-heap JVM reserves a fraction of physical RAM up front. With NetBeans open and Adam running
# his own tests, three classes in battery34 could not get it, died before TestNG loaded, and were
# reported as DID NOT RUN - the same wording as a class that crashed, so the run looked like it had
# three faults in it and had none. All three pass in 512m, and the heaviest class here peaks nowhere
# near that.
#
# Overridable, because the number is a guess about this machine rather than a property of the tests.
JAVA_FLAGS="$JAVA_FLAGS ${TC_JAVA_HEAP:--Xmx512m}"

# Adam's own railway, hashed before and after the whole run.
#
# A test class can watch its OWN writes - testTheGoldenLayoutHoldsTogether does - but not
# another class's, and the write that actually happened came from a class that had no idea it
# was near his layout: two of them start the real window, which opens whatever the saved UI
# state names.
#
# It went unnoticed for two days.  This is the scope that would have caught it on the first run.
LIVE="cs2_sample_layout"

fingerprint()
{
    if [ -d "$LIVE" ]
    then
        # Carriage returns stripped before hashing.
        #
        # Git checks these files out with CRLF and the application writes them with LF, so a
        # file rewritten with identical content still differs byte for byte.  Reporting that
        # would make this guard fire on every run, and a guard that always fires is one nobody
        # reads - which is the failure this whole check exists to prevent, arriving from the
        # other side.
        find "$LIVE" -type f -print0 2>/dev/null | sort -z | while IFS= read -r -d "" f
        do
            printf "%s  %s\n" "$(tr -d "\r" < "$f" | sha256sum | cut -d" " -f1)" "$f"
        done
    fi
}

live_before=$(fingerprint)

pass=0
fail=0
skip=0
failed=""
skipped=""

for f in $(find test -name "*.java" | sort)
do
    cls=$(echo "$f" | sed 's|^test/||; s|\.java$||; s|/|.|g')

    case "$cls" in *.*) ;; *) continue;; esac

    # Skipped for the reason build.xml gives: it "probes the network for a real Central Station at a
    # hardcoded address" and blocks until that answers. It hung this runner for fourteen minutes.
    case "$cls" in *testAutoDetect) echo "SKIP $cls (needs a Central Station)"; continue;; esac

    # Only THIS RUN's leftover JVMs - reap.ps1 says why that is narrower than "every test JVM", and
    # narrower again than "every java.exe".
    powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$(pwd)/tools/reap.ps1" \
        -RunId "$RUN_ID" >/dev/null 2>&1

    # The WHOLE output, not its last few lines (found 2026-08-25).
    #
    # This was `| tail -4`, and it turned a green class into "DID NOT RUN". TestNG prints its summary
    # and then anything the JVM still has to say - and core.testAutonomySimulationSanity ends with a
    # Marklin packet dump from a socket timing out, so the summary had scrolled past by line four.
    #
    # That is the third harness defect in this round that reported a false result rather than an
    # error, and they all have the same shape: the runner decided what a run meant by looking at part
    # of it. It is cheap to read all of it.
    out=$("$JAVA" $JAVA_FLAGS -cp "$CP" org.testng.TestNG -testclass "$cls" -d "$S/tng-run/$cls" 2>&1)

    # The LAST one, because a class can print the word before it finishes - and the last summary is
    # the one that describes the whole run.
    summary=$(echo "$out" | grep 'Total tests run' | tail -1)

    # TestNG's summary is TWO lines, and this read one (found 2026-08-25, by review).
    #
    #     Total tests run: 1, Failures: 0, Skips: 0
    #     Configuration Failures: 1, Skips: 0
    #
    # A class whose @AfterClass throws prints exactly that, and the first line alone says green.  The
    # teardowns in this suite are load-bearing: testBothProtectingSignalsAreThrown puts two of Adam's
    # real signals back to GREEN in its teardown and says why, and testARouteDoesNotThrowSwitchesUnderATrain
    # clears the auto layout in its own.  A teardown that threw would leave the railway changed and be
    # reported as a clean run.
    configFailures=$(echo "$out" | grep 'Configuration Failures' | tail -1)

    if [ -z "$summary" ]
    then
        # A class that produced no summary did not run.  Reported as a failure on purpose: a runner
        # that reads only "Failures:" calls a class that never started clean.
        # SAY WHICH KIND, because the two need opposite responses.  A JVM that could not reserve
        # its heap is the machine being busy, and the answer is to run it again; anything else is the
        # class, and the answer is to go and read it.  They read identically before this, which cost a
        # round of hunting for a fault in three classes that were fine.
        # BOTH WORDINGS, and neither is the one this first grepped for.  A 64-bit JDK 8 says
        # "Unable to allocate NNN bitmaps ... for the requested NNNKB heap" when -Xmx cannot be met,
        # and its other reservation message embeds the size - "Could not reserve enough space for
        # %I64uKB object heap" - so matching the bare sentence matched neither, and the branch was
        # dead for the very incident it was written for.
        if echo "$out" | grep -qE "Could not reserve enough space|Unable to allocate.*heap"
        then
            fail=$((fail+1)); failed="$failed\n  $cls: DID NOT RUN - no heap (machine busy, rerun)"
        else
            fail=$((fail+1)); failed="$failed\n  $cls: DID NOT RUN"
        fi

    elif ! echo "$summary" | grep -q "Failures: 0"
    then
        fail=$((fail+1)); failed="$failed\n  $cls: $summary"

    elif [ -n "$configFailures" ] && ! echo "$configFailures" | grep -q "Configuration Failures: 0"
    then
        fail=$((fail+1)); failed="$failed\n  $cls: $summary / $configFailures"

    elif echo "$summary" | grep -q "Total tests run: 0"
    then
        # ZERO tests is not zero failures (found 2026-08-25, by review).
        #
        # The skip fix below catches "Skips: N".  A class that discovers no tests at all prints
        # "Total tests run: 0, Failures: 0, Skips: 0", which satisfies both of those and landed in the
        # pass branch - so support/CS3TestServer.java and support/TestStationAddress.java, which hold
        # no tests, were counted among the green on every run.  The number was inflated by two.
        #
        # The same shape catches a class that has lost its @Test annotations, or was disabled for
        # debugging and never restored.  Counted with the skips rather than as a failure, for the same
        # reason: it needs looking at, not alarming about.
        skip=$((skip+1)); skipped="$skipped\n  $cls: $summary (no tests in this class)"

    elif echo "$summary" | grep -q "Skips: 0"
    then
        pass=$((pass+1))

    else
        # GREEN IS NOT "no failures" (found 2026-08-25).
        #
        # A class whose @BeforeClass throws reports every one of its tests as SKIPPED and none as
        # failed, so "Failures: 0" was true of a class that had tested nothing at all.
        # core.testAutonomyDiagramSampleLayout sat like that - 13 tests, 0 passed, 13 skipped -
        # and every battery in this session counted it among the green.  The stale coordinate that
        # broke it went in with the fixture separation and nothing said a word for two days.
        #
        # Counted apart rather than as a failure, because a skip can be legitimate: several
        # classes need a display and say so.  The point is that it must not read as "fine".
        skip=$((skip+1)); skipped="$skipped\n  $cls: $summary"
    fi
done

live_after=$(fingerprint)

echo "classes green: $pass   classes with failures: $fail   classes that tested nothing: $skip"
echo -e "$failed"

if [ "$skip" -gt 0 ]
then
    echo ""
    echo "These classes reported no failures because they ran nothing.  A skipped class is not a"
    echo "green class - check whether the skip is deliberate (needing a display) or a broken setup:"
    echo -e "$skipped"
fi

if [ "$live_before" != "$live_after" ]
then
    echo ""
    echo "*** THE TEST SUITE WROTE TO $LIVE ***"
    echo ""
    echo "That folder is Adam's real railway and holds his accumulated autonomy setup, which is"
    echo "not recoverable.  Find the class that did it before trusting anything above."
    echo ""
    echo "BUT FIRST: was TrainControl open while this ran?  The application writes to that folder"
    echo "too - every train that moves rewrites its placement - and this check hashes the folder"
    echo "before and after the whole run, so it cannot tell the two apart.  Changes to 'loc' and"
    echo "'facing' in configuration-*.json are what a running railway looks like; changes to"
    echo "setup.json, or a file appearing or disappearing, are not.  Look at the diff before"
    echo "hunting for a class."
    echo ""
    diff <(echo "$live_before") <(echo "$live_after") | grep '^[<>]' | sed 's/^/  /'
fi

# And an EXIT CODE, so this can be read by something other than a person.
#
# The script reported failures as text and exited on whatever the last `if` happened to leave behind,
# which is success.  Nothing reads it that way today - it is read by eye - so this costs nothing now
# and stops being a trap the first time somebody puts it behind `&&` or in CI, which is exactly when
# nobody would be watching the text.
#
# A class that tested nothing counts.  It is not a failure, but it is not a pass either, and a caller
# asking "was this run good" is asking about both.  The text above distinguishes them; the code does
# not have to.
if [ "$fail" -gt 0 ] || [ "$live_before" != "$live_after" ]
then
    exit 1
fi

if [ "$skip" -gt 0 ]
then
    exit 2
fi

exit 0
