package ui;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import static org.testng.Assert.*;
import org.testng.SkipException;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import org.traincontrol.automation.Edge;
import org.traincontrol.automation.Layout;
import org.traincontrol.automation.Point;
import org.traincontrol.automationui.AutonomySession;
import org.traincontrol.automationui.GraphReducer;
import org.traincontrol.automationui.TileGraph.TileKey;
import org.traincontrol.base.LayoutDiagramComponent;
import org.traincontrol.base.Locomotive;
import org.traincontrol.gui.LayoutLabel;
import org.traincontrol.gui.TrainControlUI;
import org.traincontrol.marklin.MarklinControlStation;
import static org.traincontrol.marklin.MarklinControlStation.init;

/**
 * W7B-B1, and Adam's ruling on it - **the grey appears at idle too, and it is regenerated by the
 * gestures that change it**.
 *
 * Adam, 2026-09-09: *"yes, this greyout should appear at idle and be regenerated if a placement or
 * train/track length is changed."*
 *
 * **What the fence cost.**  The REFUSAL over a standing train's tail has never been fenced on a
 * running railway - `Layout.isPathClear` sweeps the covered edges in every tier at every time, which
 * is right, because a tail lying across the rail is a physical fact rather than a preference.  The
 * DRAWING was fenced: *"can we just grey out the tiles just like blocked edges while autonomy is
 * running?"*  So with nothing running, a right-click manual send across a parked train's tail was
 * refused over track the diagram painted as free - which is the very complaint (*"a square the
 * railway would not let a train onto looked exactly like free track"*) that brought the grey back on
 * 2026-09-09 for the running case.  The guard and the affordance have to ask one question
 * (OB-057/OB-090), and now they do.
 *
 * **Four claims, and they are different claims.**
 *
 * - The grey is THERE at idle, on a square the railway refuses and no train is drawn on.  Asserted in
 *   pixels, because whether a square is greyed is decided when the tile is PAINTED - every
 *   model-level assertion available answers identically with the grey present and absent, which is
 *   the lesson OB-180 and `support.Rendered` were written for.
 * - It is REGENERATED when a locomotive is placed or removed.
 * - It is REGENERATED when a train's length changes.
 * - It is REGENERATED when a tile's length changes.
 *
 * **The three regeneration claims drive a production door and never ask for a refresh.**  That is the
 * whole of what they are for: `support.CoveredMarks.refresh` calls the window's private recompute, so
 * a test that called it after the gesture would prove only that the recompute works - which the first
 * claim already proves.  What is under test is whether the DOOR asks.  So each gesture goes through
 * the code the operator's hand reaches, and the test only WAITS afterwards
 * (`support.CoveredMarks.settle`), because the marks are worked out on a worker (OB-192) and asking
 * and reading are two moments.
 *
 * **Which doors, and why those.**
 *
 * - Removal: `TrainControlUI.locomotiveGestureOnDiagram` with Delete, which is the diagram's own
 *   keyboard door - *"Control+X takes the locomotive off the hovered square and remembers it, Control+V
 *   puts one down, and Delete takes one off without remembering."*  Delete rather than Control+X so
 *   that nothing lands on the clipboard, and rather than Control+V so that no arrival-side dialog can
 *   open and block the test on a modal.
 * - Train length: `TrainControlUI.applyTrainLength`, which is everything `promptTrainLength` does once
 *   the dialog has answered.  The dialog itself cannot be driven from a test without a robot, and the
 *   half that matters is the half after it; `regression.testEditorSurfaceRules` pins the call site so
 *   that extracting the rule cannot leave the caller behind.
 * - Tile length: `TrainControlUI.rebuildRunningLayoutFromSetup`, which is what
 *   `AutonomyEditorPanel.setupChanged` posts after the length is written.  A tile length can only
 *   reach the marks through a rebuild - edge lengths are baked into the built `Layout`, unlike train
 *   lengths, which `Layout.edgesCoveredByStandingTrains` reads off the locomotive every time it is
 *   asked.
 *
 * **The blocked extent is worked out here from the railway rather than asked of the window**, the same
 * way `ui.testBlockedTrackIsGreyWhileAutonomyRuns` does it and for the same reason: the claim is that
 * what is drawn is what `Layout.edgesCoveredByStandingTrains` refuses, and asking the window would be
 * asking the thing under test what the right answer is.
 *
 * **Unmeasured track is how the tile-length gesture is made visible.**  Behaviour.md 5c: the tail walk
 * *"stops at unmeasured track.  Only positive lengths are determinate."*  So measuring every square as
 * one unit blocks track and measuring every square as none blocks nothing, and the difference between
 * those two is a tile-length change with everything else held still.
 *
 * MUTATION, both measured rather than reasoned:
 *
 * - Put the `isAutonomyBusy()` fence back on the blocked set in `TrainControlUI.workOutCoveredTrack`
 *   and five of the seven fail - everything except the two controls, `testFreeTrackIsNotTouchedAtIdle`
 *   and the wash-shape claim that depends on the first.
 * - Take `blockedTrackChanged()` out of `TrainControlUI.applyTrainLength` and three fail:
 *   `testATrainLengthChangeRegeneratesTheGreyAtIdle`, which is the claim, and the two pixel claims,
 *   because the reference picture - the same square with nothing standing on it - is taken through
 *   that same door and becomes a copy of the picture it is being compared with.  Worth writing down:
 *   it means the two pixel claims cannot tell that failure from the fence's, and the set-level claim
 *   is the one that names it.
 *
 * @author Adam
 */
public class testTheGreyAppearsAtIdleToo
{
    private static support.LayoutSandbox sandbox;
    private static MarklinControlStation model;
    private static TrainControlUI ui;
    private static AutonomySession session;
    private static Layout layout;

    /** The parent these labels are given, so they and the window's own can never evict each other. */
    private static final JPanel OURS = new JPanel();

    private static final int TILE = 30;

    private static Locomotive train;
    private static Integer trainLengthWas;

    /** The train length that gave the three squares. */
    private static int trainLength;

    /** A square the train is drawn on, one that is only blocked by it, and one that is neither. */
    private static TileKey coveredSquare;
    private static TileKey blockedSquare;
    private static TileKey freeSquare;

    private static LayoutLabel coveredTile;
    private static LayoutLabel blockedTile;
    private static LayoutLabel freeTile;

    /** Each of the three squares, painted at idle with the train standing, and with nothing standing. */
    private static BufferedImage idleCovered;
    private static BufferedImage idleBlocked;
    private static BufferedImage idleFree;

    private static BufferedImage bareCovered;
    private static BufferedImage bareBlocked;
    private static BufferedImage bareFree;

    /** What the WINDOW held blocked after each gesture, with nobody asking it to recompute. */
    private static Set<TileKey> windowBlockedAtIdle;
    private static Set<TileKey> windowBlockedAfterLengthZero;
    private static Set<TileKey> windowBlockedAfterLengthBack;
    private static Set<TileKey> windowBlockedWithTilesUnmeasured;
    private static Set<TileKey> windowBlockedWithTilesMeasured;
    private static Set<TileKey> windowBlockedAfterRemoval;

    /** And what the RAILWAY held blocked at the same two moments, for the tile-length claim. */
    private static Set<TileKey> railwayBlockedWithTilesUnmeasured;
    private static Set<TileKey> railwayBlockedWithTilesMeasured;

    /** Whether the tile-length gesture actually rebuilt, so its claim cannot pass by measuring nothing. */
    private static boolean theRebuildHappened;

    @BeforeClass
    public static void setUpClass() throws Exception
    {
        if (java.awt.GraphicsEnvironment.isHeadless())
        {
            throw new SkipException("painting a tile needs a display");
        }

        // THE FROZEN COPY, NOT THE RAILWAY HE IS OPERATING (OB-111, and `test/layouts/live-snapshot`).
        //
        // `Scenario.folderFor` rather than a path: it is the only naming of a fixture folder that
        // cannot spell its way out to the operator's own railway, and `LayoutSandbox` still copies
        // what it names before anything reads it.
        sandbox = support.LayoutSandbox.open(support.Scenario.folderFor("live-snapshot"));

        model = init(null, true, true, false, true);
        model.setNetworkCommState(false);

        ui = (TrainControlUI) model.getGUI();

        assertNotNull(ui, "there is no window");

        pump();
        pump();

        session = ui.getAutonomySession();

        if (session == null) throw new SkipException("no autonomy setup on this railway");

        SwingUtilities.invokeAndWait(() -> measureEveryTileAs(1));

        model.parseAuto(session.buildConfiguration());

        layout = model.getAutoLayout();

        // THE CONFIGURATION THE REBUILD LOADS, which its first guard reads (as
        // `regression.testAPendingTurnSurvivesTheRebuild` sets it, and for the reason it gives): a
        // null makes `rebuildRunningLayoutFromSetup` a no-op, and a test whose subject silently does
        // nothing is the failure mode this repository keeps finding.
        if (ui.getActiveDiagramConfiguration() == null)
        {
            String active = session.getStore().getActiveConfiguration();

            if (active == null) throw new SkipException("the snapshot names no active configuration");

            Field field = TrainControlUI.class.getDeclaredField("activeDiagramConfiguration");

            field.setAccessible(true);
            field.set(ui, active);
        }

        // NOTHING IS RUNNING, and this class is about nothing running.  Asserted rather than assumed:
        // every claim below would be about the old, fenced behaviour if a run had somehow started.
        assertFalse(layout.isRunning(),
            "the frozen railway came up with autonomy running, so every claim here is about the wrong"
            + " state");

        oneTrainThatCoversSomething();

        if (train == null) throw new SkipException("no standing train covers any track here");

        if (!chooseTheThreeSquares())
        {
            throw new SkipException(
                "no train on this railway blocks a square it is not drawn on, so the two marks "
                + "cannot be told apart here");
        }

        coveredTile = drawnTileFor(coveredSquare);
        blockedTile = drawnTileFor(blockedSquare);
        freeTile = drawnTileFor(freeSquare);

        // AT IDLE, with the train exactly where it is.
        train.setTrainLength(trainLength);

        support.CoveredMarks.refresh(ui);

        pump();

        repaintTheThree();

        idleCovered = paint(coveredTile);
        idleBlocked = paint(blockedTile);
        idleFree = paint(freeTile);

        windowBlockedAtIdle = whatTheWindowHoldsBlocked();

        // AND AT IDLE WITH NOTHING STANDING ANYWHERE, which is the reference every "is this square
        // marked at all" question is asked against.  A length of zero is how this railway says "not
        // set", and an unmeasured train covers nothing.
        //
        // THROUGH THE DOOR, and nobody asks for a refresh afterwards: this is the train-length
        // gesture as well as the reference picture.
        SwingUtilities.invokeAndWait(() -> ui.applyTrainLength(train, 0));

        pump();

        support.CoveredMarks.settle(ui);

        windowBlockedAfterLengthZero = whatTheWindowHoldsBlocked();

        repaintTheThree();

        bareCovered = paint(coveredTile);
        bareBlocked = paint(blockedTile);
        bareFree = paint(freeTile);

        // AND BACK, so the gesture is shown in both directions - putting the wash on is the half a
        // set comparison makes easy to forget.
        SwingUtilities.invokeAndWait(() -> ui.applyTrainLength(train, trainLength));

        pump();

        support.CoveredMarks.settle(ui);

        windowBlockedAfterLengthBack = whatTheWindowHoldsBlocked();

        captureTheTileLengthGesture();

        captureTheRemovalGesture();
    }

    @AfterClass(alwaysRun = true)
    public static void tearDownClass() throws Exception
    {
        try
        {
            if (model != null && model.hasAutoLayout()) model.getAutoLayout().stopLocomotives();

            // PUT BACK: init() opens Adam's own locomotive database, and a length this test chose is
            // not a measurement of his train.
            if (train != null) train.setTrainLength(trainLengthWas == null ? 0 : trainLengthWas);
        }
        finally
        {
            if (sandbox != null) sandbox.close();
        }
    }

    // ---------------------------------------------------------------- the grey is there at idle

    /**
     * A square nothing is drawn on, but which the railway refuses, is greyed with nothing running.
     */
    @Test
    public void testBlockedTrackIsGreyAtIdle()
    {
        assertEquals(orangePixels(idleBlocked), 0,
            "the orange line is drawn on " + blockedSquare + ", so it is a square the train is shown "
            + "on rather than one merely blocked by it, and this test is asking about the wrong tile");

        assertTrue(brightness(idleBlocked) < brightness(bareBlocked) - 2.0,
            "the square " + blockedSquare + " is drawn no darker while a standing train blocks it ("
            + brightness(idleBlocked) + ") than with nothing standing anywhere ("
            + brightness(bareBlocked) + "), and NOTHING IS RUNNING.  The refusal is not fenced on a "
            + "running railway - `Layout.isPathClear` sweeps the covered edges in every tier - so a "
            + "manual send across this square is refused while the diagram paints it as free "
            + "(W7B-B1).  Adam: \"yes, this greyout should appear at idle\"");
    }

    /**
     * And it is grey rather than another line: the whole square is darkened, not a stroke across it.
     */
    @Test(dependsOnMethods = "testBlockedTrackIsGreyAtIdle")
    public void testTheIdleMarkIsAWashOverTheWholeSquare()
    {
        int changed = differingPixels(idleBlocked, bareBlocked);

        int all = TILE * TILE;

        assertTrue(changed > all / 2,
            "only " + changed + " of the square's " + all + " pixels change when it becomes blocked "
            + "at idle, so the mark is a line along part of it rather than the tile being greyed");
    }

    /**
     * A square that is both - the train is on it AND it is blocked - reads as both, at idle as well.
     */
    @Test
    public void testASquareWithATrainOnItIsStillOrangeAtIdle()
    {
        assertTrue(orangePixels(idleCovered) > 0,
            "the train on " + coveredSquare + " cannot be seen at idle, so either it is not drawn at "
            + "all or the wash has been laid OVER the line rather than under it");

        assertTrue(brightness(idleCovered) < brightness(bareCovered) - 2.0,
            "the square the train stands on is drawn no darker at idle with the train standing ("
            + brightness(idleCovered) + ") than with nothing standing (" + brightness(bareCovered)
            + "), so the square carrying the train is the one square that does not say it is blocked");
    }

    /**
     * CONTROL - track no train blocks is left alone at idle.
     *
     * Without this every assertion above is satisfied by greying the whole page.
     */
    @Test
    public void testFreeTrackIsNotTouchedAtIdle()
    {
        assertTrue(support.Rendered.same(idleFree, bareFree),
            "the square " + freeSquare + ", which no train covers or blocks, is drawn differently at "
            + "idle while a train stands elsewhere - the wash is being laid over track that is free");
    }

    // ---------------------------------------------------------------- and it is regenerated

    /**
     * A train's length changing regenerates the grey, with nothing running.
     *
     * Adam: *"...and be regenerated if a placement or train/track length is changed."*
     */
    @Test
    public void testATrainLengthChangeRegeneratesTheGreyAtIdle()
    {
        assertFalse(windowBlockedAtIdle.isEmpty(),
            "the window holds nothing blocked at idle even with the train standing, so there is no "
            + "grey for a length change to regenerate and this test measures nothing");

        assertTrue(windowBlockedAfterLengthZero.isEmpty(),
            "setting the train's length to zero - which is how this railway says \"not set\", and an "
            + "unmeasured train covers nothing - left the window still holding "
            + windowBlockedAfterLengthZero.size() + " squares blocked.  Nobody asked it to recompute "
            + "after the change, and nothing on the length door did either, so the diagram is greying "
            + "track that is no longer blocked");

        assertEquals(windowBlockedAfterLengthBack, windowBlockedAtIdle,
            "measuring the train again did not bring the grey back to what it was.  Taking a mark off "
            + "and putting it on are two halves of one gesture and only one of them was wired");
    }

    /**
     * A tile's length changing regenerates the grey, with nothing running.
     */
    @Test
    public void testATileLengthChangeRegeneratesTheGreyAtIdle()
    {
        assertTrue(theRebuildHappened,
            "the setup rebuild left the running Layout in place, so the tile lengths never reached "
            + "the railway and this test measured nothing.  `rebuildRunningLayoutFromSetup` is a "
            + "no-op without an active configuration, with autonomy busy, or with no viewer panel");

        // THE GESTURE MOVED THE RAILWAY'S OWN ANSWER, so the comparison below is not two copies of
        // one number.  Measuring every square as none shortens what a tail can reach - behaviour.md
        // 5c: the walk *"stops at unmeasured track.  Only positive lengths are determinate."*
        assertNotEquals(railwayBlockedWithTilesUnmeasured, railwayBlockedWithTilesMeasured,
            "the railway blocks exactly the same squares whether every tile measures one unit or "
            + "none, so writing tile lengths changed nothing and there is nothing for the diagram to "
            + "have followed.  Both answers: " + railwayBlockedWithTilesMeasured);

        assertFalse(railwayBlockedWithTilesMeasured.isEmpty(),
            "the railway blocks nothing at all once the track is measured again, so the standing "
            + "train did not survive the rebuild and this test is measuring an empty railway");

        assertEquals(windowBlockedWithTilesUnmeasured, railwayBlockedWithTilesUnmeasured,
            "after a tile-length change the diagram is greying "
            + windowBlockedWithTilesUnmeasured.size() + " squares and the railway is refusing "
            + railwayBlockedWithTilesUnmeasured.size() + ".  Nobody asked the window to recompute "
            + "after the setup rebuild, so the wash still describes the lengths before last");

        assertEquals(windowBlockedWithTilesMeasured, railwayBlockedWithTilesMeasured,
            "measuring the track again did not bring the grey back to what the railway refuses.  "
            + "Taking a mark off and putting it on are two halves of one gesture and only one of them "
            + "was wired");
    }

    /**
     * Taking the train off its square regenerates the grey, with nothing running.
     *
     * Through the diagram's own Delete key, which is the door Adam uses.
     */
    @Test
    public void testRemovingATrainTakesTheGreyOffAtIdle()
    {
        assertFalse(windowBlockedAtIdle.isEmpty(),
            "the window holds nothing blocked at idle even with the train standing, so there is no "
            + "grey for a removal to take off and this test measures nothing");

        assertTrue(windowBlockedAfterRemoval.isEmpty(),
            "pressing Delete over the square the train stands on took the train off the railway and "
            + "left " + windowBlockedAfterRemoval.size() + " squares still greyed.  Adam: \"when a "
            + "train is manually moved to a new station in the track diagram viewer using control+X "
            + "and V, its former shaded icons are not reset\" - the same complaint, one key over");
    }

    // ---------------------------------------------------------------- the gestures

    /**
     * Measures every square as none, rebuilds, and measures them as one again.
     *
     * A tile length can only reach the marks through a rebuild: edge lengths are baked into the built
     * `Layout` by `GraphReducer`, unlike train lengths, which `edgesCoveredByStandingTrains` reads off
     * the locomotive every time it is asked.  `rebuildRunningLayoutFromSetup` is exactly what
     * `AutonomyEditorPanel.setupChanged` posts once a length has been written.
     */
    private static void captureTheTileLengthGesture() throws Exception
    {
        Layout before = model.getAutoLayout();

        SwingUtilities.invokeAndWait(() -> measureEveryTileAs(0));

        SwingUtilities.invokeAndWait(() -> ui.rebuildRunningLayoutFromSetup());

        pump();
        pump();

        support.CoveredMarks.settle(ui);

        theRebuildHappened = model.getAutoLayout() != before;

        // The rebuild replaced the object; the railway's own answer has to be asked of the new one.
        layout = model.getAutoLayout();

        railwayBlockedWithTilesUnmeasured = blockedSquares();
        windowBlockedWithTilesUnmeasured = whatTheWindowHoldsBlocked();

        SwingUtilities.invokeAndWait(() -> measureEveryTileAs(1));

        SwingUtilities.invokeAndWait(() -> ui.rebuildRunningLayoutFromSetup());

        pump();
        pump();

        support.CoveredMarks.settle(ui);

        layout = model.getAutoLayout();

        railwayBlockedWithTilesMeasured = blockedSquares();
        windowBlockedWithTilesMeasured = whatTheWindowHoldsBlocked();
    }

    /**
     * Presses Delete over the square the train stands on, which is the diagram's own removal door.
     *
     * Delete rather than Control+X so that nothing lands on the clipboard, and rather than Control+V
     * so that no arrival-side dialog can open and block this on a modal.
     */
    private static void captureTheRemovalGesture() throws Exception
    {
        final TileKey square = squareOfTheStandingTrain();

        if (square == null)
        {
            windowBlockedAfterRemoval = new LinkedHashSet<>();

            throw new SkipException("the standing train's square cannot be named, so the diagram's"
                + " own Delete door cannot be aimed at it");
        }

        final Method gesture = TrainControlUI.class.getDeclaredMethod(
            "locomotiveGestureOnDiagram", int.class, boolean.class);

        gesture.setAccessible(true);

        final Object[] handled = new Object[1];

        SwingUtilities.invokeAndWait(() ->
        {
            try
            {
                ui.setHoveredDiagramTile(square.getPage(), square.getX(), square.getY());

                handled[0] = gesture.invoke(ui, KeyEvent.VK_DELETE, false);
            }
            catch (Exception refused)
            {
                handled[0] = refused;
            }
        });

        assertEquals(handled[0], Boolean.TRUE,
            "the diagram's Delete door declined the square the train is standing on (" + square
            + "), so nothing was removed and the claim below would pass by having changed nothing: "
            + handled[0]);

        pump();
        pump();

        // THE GESTURE ACTUALLY TOOK THE TRAIN OFF, asserted rather than assumed.  `true` is also what
        // this door returns when it REFUSES - autonomy busy, an editor open, no autonomy Point on the
        // square - each with a line in the log and nothing changed.  Without this, a refusal would
        // leave the grey exactly as it was and the claim below would report the diagram at fault.
        assertNull(squareOfTheStandingTrain(),
            "the train is still standing on the railway after the diagram's Delete door was pressed"
            + " over its square, so the door declined and nothing was removed");

        support.CoveredMarks.settle(ui);

        windowBlockedAfterRemoval = whatTheWindowHoldsBlocked();
    }

    /** The diagram square the one standing train is on, or null. */
    private static TileKey squareOfTheStandingTrain()
    {
        for (Point point : layout.getPoints())
        {
            if (point.getCurrentLocomotive() == null) continue;

            if (!point.getCurrentLocomotive().getName().equals(train.getName())) continue;

            TileKey square = session.getStationIndex() == null
                ? null : session.getStationIndex().squareOf(point.getName());

            if (square != null) return square;
        }

        return null;
    }

    // ---------------------------------------------------------------- what each side says

    /**
     * The squares the WINDOW is holding blocked, read off the cache the tiles are drawn from.
     *
     * Asked of every square the reduction knows, because there is no getter for the set itself and
     * `isTrackBlocked` is the question the tile asks.
     *
     * @return the blocked squares
     */
    private static Set<TileKey> whatTheWindowHoldsBlocked()
    {
        Set<TileKey> out = new LinkedHashSet<>();

        for (TileKey square : everyTile())
        {
            if (ui.isTrackBlocked(square)) out.add(square);
        }

        return out;
    }

    /**
     * The squares the RAILWAY holds blocked, worked out from the covered EDGES.
     *
     * Not asked of the window: the window is what is under test, and a test that asks it what the
     * answer is agrees with it whatever it says.  This is the translation `AutonomySession` performs -
     * a covered `Edge` runs between two `Point`s, each `Point` maps back to a square, and the reducer
     * holds the tiles lying between two squares - with the endpoints excluded, because a train
     * standing at a sensor is shown standing there and the points are technically unoccupied.
     *
     * @return the blocked squares
     */
    private static Set<TileKey> blockedSquares()
    {
        Set<TileKey> out = new LinkedHashSet<>();

        for (Edge edge : layout.edgesCoveredByStandingTrains().keySet())
        {
            if (edge == null || edge.getStart() == null || edge.getEnd() == null) continue;

            TileKey from = session.getStationIndex().squareOf(edge.getStart().getName());
            TileKey to = session.getStationIndex().squareOf(edge.getEnd().getName());

            if (from == null || to == null) continue;

            for (GraphReducer.ReducedEdge reduced : session.getReducer().getEdges())
            {
                boolean sameWay = from.equals(reduced.getStart()) && to.equals(reduced.getEnd());
                boolean otherWay = to.equals(reduced.getStart()) && from.equals(reduced.getEnd());

                if (!sameWay && !otherWay) continue;

                for (GraphReducer.TileStep step : reduced.getPath())
                {
                    if (step.getTile() == null) continue;

                    if (step.getTile().equals(from) || step.getTile().equals(to)) continue;

                    out.add(step.getTile());
                }

                break;
            }
        }

        return out;
    }

    /**
     * Finds a train length at which the railway blocks a square the train is not drawn on.
     *
     * Both marks have to be visible at once for any of this to be assertable, and how far each of them
     * reaches depends on the length: the line is as long as the train, the blocked extent is whole
     * edges.  A short train on a long edge separates them, and how short depends on the railway.
     *
     * @return true when all three squares were found
     */
    private static boolean chooseTheThreeSquares() throws Exception
    {
        for (int length = 1; length <= 6; length++)
        {
            train.setTrainLength(length);

            support.CoveredMarks.refresh(ui);

            pump();

            Set<TileKey> blocked = blockedSquares();

            TileKey onTheTrain = null;
            TileKey blockedOnly = null;

            for (TileKey square : everyTile())
            {
                if (ui.isTrackCovered(square))
                {
                    if (onTheTrain == null && drawable(square)) onTheTrain = square;
                }
                else if (blocked.contains(square))
                {
                    if (blockedOnly == null && drawable(square)) blockedOnly = square;
                }
            }

            if (onTheTrain == null || blockedOnly == null) continue;

            TileKey free = null;

            for (TileKey square : everyTile())
            {
                if (ui.isTrackCovered(square) || blocked.contains(square)) continue;

                if (drawable(square))
                {
                    free = square;

                    break;
                }
            }

            if (free == null) continue;

            coveredSquare = onTheTrain;
            blockedSquare = blockedOnly;
            freeSquare = free;
            trainLength = length;

            return true;
        }

        return false;
    }

    private static boolean drawable(TileKey square)
    {
        org.traincontrol.base.LayoutDiagram page = model.getLayout(square.getPage());

        if (page == null) return false;

        LayoutDiagramComponent component = page.getComponent(square.getX(), square.getY());

        return component != null && !component.isText();
    }

    // ---------------------------------------------------------------- looking at the picture

    /**
     * Whether this colour is the orange a person would call orange.
     *
     * The same test `support.Rendered` and `ui.testTheTrainIsShownAsALine` use, by hue rather than
     * against production's own constant: the claim is about what somebody looking at the diagram
     * sees, and a test reading the constant would agree with any value it was changed to.
     */
    private static boolean isOrange(int rgb)
    {
        int r = (rgb >> 16) & 0xFF;
        int g = (rgb >> 8) & 0xFF;
        int b = rgb & 0xFF;

        return r > 190 && g > 70 && g < 190 && b < 90 && r - g > 60;
    }

    private static int orangePixels(BufferedImage image)
    {
        int found = 0;

        for (int x = 0; x < image.getWidth(); x++)
        {
            for (int y = 0; y < image.getHeight(); y++)
            {
                if (isOrange(image.getRGB(x, y))) found++;
            }
        }

        return found;
    }

    private static double brightness(BufferedImage image)
    {
        return support.Rendered.brightness(image);
    }

    private static int differingPixels(BufferedImage a, BufferedImage b)
    {
        int found = 0;

        for (int x = 0; x < a.getWidth(); x++)
        {
            for (int y = 0; y < a.getHeight(); y++)
            {
                if (a.getRGB(x, y) != b.getRGB(x, y)) found++;
            }
        }

        return found;
    }

    /**
     * Paints one tile, on its own, exactly as the diagram paints it.
     *
     * `paint` and not `printAll`: both of those begin with an isShowing() check and do nothing for a
     * component that is not on screen, which is every component here.
     */
    private static BufferedImage paint(final LayoutLabel label) throws Exception
    {
        final BufferedImage[] shot = new BufferedImage[1];

        SwingUtilities.invokeAndWait(() ->
        {
            label.setSize(TILE, TILE);

            shot[0] = new BufferedImage(TILE, TILE, BufferedImage.TYPE_INT_RGB);

            Graphics2D g = shot[0].createGraphics();

            try
            {
                g.setColor(Color.WHITE);
                g.fillRect(0, 0, TILE, TILE);

                label.paint(g);
            }
            finally
            {
                g.dispose();
            }
        });

        return shot[0];
    }

    // ---------------------------------------------------------------- the fixture

    private static void repaintTheThree() throws Exception
    {
        SwingUtilities.invokeAndWait(() ->
        {
            coveredTile.refreshCoveredMark();
            blockedTile.refreshCoveredMark();
            freeTile.refreshCoveredMark();
        });

        pump();
    }

    /**
     * A real tile for a square, drawn and ready to be painted.
     */
    private static LayoutLabel drawnTileFor(TileKey square) throws Exception
    {
        org.traincontrol.base.LayoutDiagram page = model.getLayout(square.getPage());

        LayoutDiagramComponent component = page.getComponent(square.getX(), square.getY());

        final LayoutLabel[] built = new LayoutLabel[1];

        SwingUtilities.invokeAndWait(() ->
        {
            built[0] = new LayoutLabel(component, OURS, TILE, ui, false);
            built[0].setSquare(square);
        });

        ui.getDiagramTileRegistry().register(square, built[0]);

        long until = System.currentTimeMillis() + 30000;

        while (built[0].getIcon() == null && System.currentTimeMillis() < until) pump();

        assertNotNull(built[0].getIcon(),
            "the tile never drew its image, so every picture below would be of an empty square");

        return built[0];
    }

    private static Set<TileKey> everyTile()
    {
        Set<TileKey> out = new LinkedHashSet<>();

        for (GraphReducer.ReducedEdge edge : session.getReducer().getEdges())
        {
            for (GraphReducer.TileStep step : edge.getPath())
            {
                if (step.getTile() != null) out.add(step.getTile());
            }
        }

        return out;
    }

    /**
     * Leaves one train standing, and only one that actually covers track - a train whose recorded
     * arrival side leads nowhere the graph can follow covers nothing, and every picture here would be
     * of an ordinary square.
     */
    private static void oneTrainThatCoversSomething()
    {
        Point keep = null;

        for (Point point : layout.getPoints())
        {
            if (point.getCurrentLocomotive() == null || point.getArrivedFrom() == null) continue;

            Locomotive candidate = point.getCurrentLocomotive();

            Integer was = candidate.getTrainLength();

            candidate.setTrainLength(4);

            boolean covers = layout.edgesCoveredByStandingTrains().containsValue(candidate);

            candidate.setTrainLength(was);

            if (covers)
            {
                keep = point;

                break;
            }
        }

        if (keep == null) return;

        for (Point point : layout.getPoints())
        {
            if (point == keep || point.getCurrentLocomotive() == null) continue;

            // OFF THE SETUP AS WELL AS OFF THE RAILWAY, which the two older covered-track classes do
            // not have to do and this one does.
            //
            // The tile-length gesture below is a setup REBUILD, and a rebuild regenerates every
            // placement from the setup: clearing the running layout alone put every other train back
            // the moment the lengths were written, and the removal gesture after it then took one
            // train off a railway carrying nine others.  What it reported was the diagram failing to
            // ungrey; what had happened is that the track really was still blocked.
            TileKey square = session.getStationIndex() == null
                ? null : session.getStationIndex().squareOf(point.getName());

            if (square != null) session.placeLocomotive(square, null);

            layout.moveLocomotive(null, point.getName(), true);
        }

        train = keep.getCurrentLocomotive();

        trainLengthWas = train.getTrainLength();

        train.setTrainLength(4);
    }

    private static void measureEveryTileAs(int units)
    {
        Set<TileKey> everyTile = new LinkedHashSet<>();

        for (TileKey tile : session.getReducer().getPoints().keySet()) everyTile.add(tile);

        for (GraphReducer.ReducedEdge edge : session.getReducer().getEdges())
        {
            for (GraphReducer.TileStep step : edge.getPath())
            {
                if (step.getTile() != null) everyTile.add(step.getTile());
            }
        }

        for (TileKey tile : everyTile) session.setTileLength(tile, units);
    }

    private static void pump() throws Exception
    {
        SwingUtilities.invokeAndWait(() -> { });
    }
}
