#!/bin/bash
#
# Runs every test class, one JVM each, and reports which ones are not green.
#
# Lived in a session scratch directory until 2026-08-25, which is why the bug below could be made
# twice: a harness nobody can read is a harness nobody can review. It is here now.
#
# Usage, from the project root:
#
#     TC_SCRATCH=/path/to/scratch bash tools/battery.sh
#
# DO NOT EDIT THIS FILE WHILE A RUN IS IN PROGRESS. Bash reads a script lazily, by byte offset, so an
# edit above the point it has reached shifts everything after it and the next read lands mid-token.
# The run may carry on looking healthy and produce a result that means nothing. If you need to change
# it during a long run, copy it first and run the copy - which is what a session on 2026-08-25 ended
# up doing, after editing it under a run and having to throw the run away.
#
# TC_SCRATCH holds cp.txt (the classpath, one line) and receives the TestNG output. See
# docs/manual-tests/README.md for how it is built.

set -u

S="${TC_SCRATCH:-}"

if [ -z "$S" ] || [ ! -f "$S/cp.txt" ]
then
    echo "TC_SCRATCH must name a directory containing cp.txt (the classpath)." >&2
    exit 2
fi

# NOT a stale compile directory first.  A leftover tree once shadowed the real one, so the battery
# silently tested old code and a method added minutes earlier came back as NoSuchMethodError.
CP="$(cat "$S/cp.txt")"

JAVA="${TC_JAVA:-/c/Program Files/Java/jdk1.8.0_361/bin/java}"

# Any free receive port instead of the Marklin one.
#
# Every class that builds a MarklinControlStation used to bind UDP 15730, so the battery could not run
# while TrainControl was open, an orphaned JVM poisoned every class after it, and two classes could
# never overlap. None of them receives anything from a Central Station - there is none - so the port
# was pure contention.
#
# The failure it removes is a nasty one to read: a bind failure comes out of @BeforeClass as
# "Total tests run: 16, Failures: 0, Skips: 16" - zero failures, having tested nothing.
JAVA_FLAGS="${TC_JAVA_FLAGS:--Dtraincontrol.anyReceivePort=true}"

# This run's own name, so the reaper can tell this battery's leftovers from anything else on the
# machine - including another battery, and including a test somebody is running by hand.
#
# Without it the reaper matched every JVM carrying the receive-port flag, which is every test JVM
# there is: a battery running in the background killed a hand-run test at exit 127 with no output,
# which reads as the test hanging rather than as something else shooting it.
RUN_ID="battery-$$"

JAVA_FLAGS="$JAVA_FLAGS -Dtraincontrol.batteryRun=$RUN_ID"

# Adam's own railway, hashed before and after the whole run.
#
# A test class can watch its OWN writes - testTheGoldenLayoutHoldsTogether does - but not
# another class's, and the write that actually happened came from a class that had no idea it
# was near his layout: two of them start the real window, which opens whatever the saved UI
# state names.
#
# It went unnoticed for two days.  This is the scope that would have caught it on the first run.
LIVE="cs2_sample_layout"

fingerprint()
{
    if [ -d "$LIVE" ]
    then
        # Carriage returns stripped before hashing.
        #
        # Git checks these files out with CRLF and the application writes them with LF, so a
        # file rewritten with identical content still differs byte for byte.  Reporting that
        # would make this guard fire on every run, and a guard that always fires is one nobody
        # reads - which is the failure this whole check exists to prevent, arriving from the
        # other side.
        find "$LIVE" -type f -print0 2>/dev/null | sort -z | while IFS= read -r -d "" f
        do
            printf "%s  %s\n" "$(tr -d "\r" < "$f" | sha256sum | cut -d" " -f1)" "$f"
        done
    fi
}

live_before=$(fingerprint)

pass=0
fail=0
skip=0
failed=""
skipped=""

for f in $(find test -name "*.java" | sort)
do
    cls=$(echo "$f" | sed 's|^test/||; s|\.java$||; s|/|.|g')

    case "$cls" in *.*) ;; *) continue;; esac

    # Skipped for the reason build.xml gives: it "probes the network for a real Central Station at a
    # hardcoded address" and blocks until that answers. It hung this runner for fourteen minutes.
    case "$cls" in *testAutoDetect) echo "SKIP $cls (needs a Central Station)"; continue;; esac

    # Only THIS RUN's leftover JVMs - reap.ps1 says why that is narrower than "every test JVM", and
    # narrower again than "every java.exe".
    powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$(pwd)/tools/reap.ps1" \
        -RunId "$RUN_ID" >/dev/null 2>&1

    out=$("$JAVA" $JAVA_FLAGS -cp "$CP" org.testng.TestNG -testclass "$cls" -d "$S/tng-run/$cls" 2>&1 | tail -4)

    summary=$(echo "$out" | grep 'Total tests run')

    if [ -z "$summary" ]
    then
        # A class that produced no summary did not run.  Reported as a failure on purpose: a runner
        # that reads only "Failures:" calls a class that never started clean.
        fail=$((fail+1)); failed="$failed\n  $cls: DID NOT RUN"

    elif ! echo "$summary" | grep -q "Failures: 0"
    then
        fail=$((fail+1)); failed="$failed\n  $cls: $summary"

    elif echo "$summary" | grep -q "Skips: 0"
    then
        pass=$((pass+1))

    else
        # GREEN IS NOT "no failures" (found 2026-08-25).
        #
        # A class whose @BeforeClass throws reports every one of its tests as SKIPPED and none as
        # failed, so "Failures: 0" was true of a class that had tested nothing at all.
        # core.testAutonomyDiagramSampleLayout sat like that - 13 tests, 0 passed, 13 skipped -
        # and every battery in this session counted it among the green.  The stale coordinate that
        # broke it went in with the fixture separation and nothing said a word for two days.
        #
        # Counted apart rather than as a failure, because a skip can be legitimate: several
        # classes need a display and say so.  The point is that it must not read as "fine".
        skip=$((skip+1)); skipped="$skipped\n  $cls: $summary"
    fi
done

live_after=$(fingerprint)

echo "classes green: $pass   classes with failures: $fail   classes that tested nothing: $skip"
echo -e "$failed"

if [ "$skip" -gt 0 ]
then
    echo ""
    echo "These classes reported no failures because they ran nothing.  A skipped class is not a"
    echo "green class - check whether the skip is deliberate (needing a display) or a broken setup:"
    echo -e "$skipped"
fi

if [ "$live_before" != "$live_after" ]
then
    echo ""
    echo "*** THE TEST SUITE WROTE TO $LIVE ***"
    echo ""
    echo "That folder is Adam's real railway and holds his accumulated autonomy setup, which is"
    echo "not recoverable.  Find the class that did it before trusting anything above."
    echo ""
    diff <(echo "$live_before") <(echo "$live_after") | grep '^[<>]' | sed 's/^/  /'
fi
